export const ARCHIVE_COPY = {
  en: {
    collectCompare: "Capture and compare",
    onlyDifferences: "Only show different paragraphs",
    noDifferentParagraphs: "No different paragraphs in this answer.",
    compareNeedsAnswers: "Saved the capture. At least two answers with text are needed to compare.",

    archiveQuestion: "Question",
    archiveSource: "Source",
    archiveBestAnswer: "Best answer",
    noAnswer: "No answer",
    collectAnswers: "Collect and copy selected answers",
    openArchive: "Open result library",
    archiveTitle: "Result library",
    closeArchive: "Close result library",
    archiveSearch: "Search questions and answers…",
    favoriteArchives: "Favorites",
    favoriteArchive: "Add to favorites",
    unfavoriteArchive: "Remove from favorites",
    allArchiveTags: "All tags",
    captureArchive: "Capture current answers",
    copyArchive: "Copy Markdown",
    exportArchive: "Export Markdown",
    deleteArchive: "Delete result",
    confirmDeleteArchive: "Delete this result? Decision cards and excerpts are retained.",
    archiveTags: "Tags",
    archiveNote: "Note",
    markBest: "Mark best",
    unmarkBest: "Unmark best",
    compareAnswers: "Compare two answers",
    closeAnswerComparison: "Close answer comparison",
    answerComparison: "Answer comparison",
    answerComparisonDescription: "Marks only paragraphs that are exactly the same. It does not judge accuracy or answer quality.",
    leftAnswer: "Left answer",
    rightAnswer: "Right answer",
    sharedParagraph: "Shared paragraph",
    uniqueParagraph: "Only in this answer",
    archiveLoading: "Loading results…",
    archiveEmpty: "No saved results yet",
    archiveNoMatches: "No matching results",
    archiveLoadFailed: "Could not load the result library",
    archiveSaveFailed: "Could not save changes",
    archiveCollectFailed: "Could not collect current answers",
    archiveCollected: "Answers saved and Markdown copied",
    archiveSaved: "Current answers saved",
    archiveCopied: "Markdown copied",
    archiveExported: "Markdown exported",
    archiveCapturedAt: "Captured {time}"
  },
  zhCN: {
    collectCompare: "采集并比较",
    onlyDifferences: "只看不同段落",
    noDifferentParagraphs: "这份回答没有不同段落。",
    compareNeedsAnswers: "已保存采集结果，至少需要两份有正文的回答才能比较。",

    archiveQuestion: "问题",
    archiveSource: "来源",
    archiveBestAnswer: "最佳回答",
    noAnswer: "暂无回答",
    collectAnswers: "汇总复制已选回答",
    openArchive: "打开结果库",
    archiveTitle: "结果库",
    closeArchive: "关闭结果库",
    archiveSearch: "搜索问题与回答…",
    favoriteArchives: "仅看收藏",
    favoriteArchive: "添加收藏",
    unfavoriteArchive: "取消收藏",
    allArchiveTags: "全部标签",
    captureArchive: "采集当前回答",
    copyArchive: "复制 Markdown",
    exportArchive: "导出 Markdown",
    deleteArchive: "删除结果",
    confirmDeleteArchive: "确认删除这条结果？决策卡及摘录仍保留。",
    archiveTags: "标签",
    archiveNote: "备注",
    markBest: "标为最佳",
    unmarkBest: "取消最佳",
    compareAnswers: "对照两份回答",
    closeAnswerComparison: "关闭回答对照",
    answerComparison: "回答对照",
    answerComparisonDescription: "仅按完全相同的段落标记共有内容，不判断事实准确性或回答优劣。",
    leftAnswer: "左侧回答",
    rightAnswer: "右侧回答",
    sharedParagraph: "共同段落",
    uniqueParagraph: "仅此回答",
    archiveLoading: "正在加载结果…",
    archiveEmpty: "暂无已保存结果",
    archiveNoMatches: "没有匹配结果",
    archiveLoadFailed: "结果库加载失败",
    archiveSaveFailed: "修改保存失败",
    archiveCollectFailed: "当前回答采集失败",
    archiveCollected: "回答已保存并复制 Markdown",
    archiveSaved: "当前回答已保存",
    archiveCopied: "已复制 Markdown",
    archiveExported: "已导出 Markdown",
    archiveCapturedAt: "采集于 {time}"
  },
  zhTW: {
    collectCompare: "擷取並比較",
    onlyDifferences: "只看不同段落",
    noDifferentParagraphs: "這份回答沒有不同段落。",
    compareNeedsAnswers: "已儲存擷取結果，至少需要兩份有正文的回答才能比較。",

    archiveQuestion: "問題",
    archiveSource: "來源",
    archiveBestAnswer: "最佳回答",
    noAnswer: "暫無回答",
    collectAnswers: "彙整複製已選回答",
    openArchive: "開啟結果庫",
    archiveTitle: "結果庫",
    closeArchive: "關閉結果庫",
    archiveSearch: "搜尋問題與回答…",
    favoriteArchives: "僅看收藏",
    favoriteArchive: "加入收藏",
    unfavoriteArchive: "取消收藏",
    allArchiveTags: "全部標籤",
    captureArchive: "擷取目前回答",
    copyArchive: "複製 Markdown",
    exportArchive: "匯出 Markdown",
    deleteArchive: "刪除結果",
    confirmDeleteArchive: "確認刪除這筆結果？決策卡及摘錄仍保留。",
    archiveTags: "標籤",
    archiveNote: "備註",
    markBest: "標為最佳",
    unmarkBest: "取消最佳",
    compareAnswers: "對照兩份回答",
    closeAnswerComparison: "關閉回答對照",
    answerComparison: "回答對照",
    answerComparisonDescription: "僅按完全相同的段落標示共有內容，不判斷事實準確性或回答優劣。",
    leftAnswer: "左側回答",
    rightAnswer: "右側回答",
    sharedParagraph: "共同段落",
    uniqueParagraph: "僅此回答",
    archiveLoading: "正在載入結果…",
    archiveEmpty: "尚無已儲存結果",
    archiveNoMatches: "沒有符合的結果",
    archiveLoadFailed: "結果庫載入失敗",
    archiveSaveFailed: "變更儲存失敗",
    archiveCollectFailed: "目前回答擷取失敗",
    archiveCollected: "回答已儲存並複製 Markdown",
    archiveSaved: "目前回答已儲存",
    archiveCopied: "已複製 Markdown",
    archiveExported: "已匯出 Markdown",
    archiveCapturedAt: "擷取於 {time}"
  }
} as const;
