export const BACKUP_COPY = {
  en: {
    backupCalculating: "Checking selected items…",
    backupYes: "Yes", backupNo: "No", backupNotSet: "Not set", backupUnknownValue: "Unrecognized value: {value}",
    backupChangedFields: "{count} changed fields", backupFullVersions: "Full versions", backupRawData: "Original data",
    backupType: "Item type", backupStatusFilter: "Item status", backupConflictsOnly: "Conflicts only",
    backupVisibleScope: "{count} visible · {selected} selected for import", backupSelectVisible: "Use backup for {count} visible items", backupClearVisible: "Keep or skip {count} visible items",
    backupBulkNotice: "Bulk choices apply only to this view. Identical and unavailable items are excluded; deleted items require an individual restore choice.",
    backupRequiredEntities: "Required items", backupDependencySelected: "Selected", backupDependencyMissing: "Unavailable on this device and in this backup", backupDependencyDeleted: "Choose restoration individually", backupDependencyBlocked: "Unavailable",
    backupAddDependencies: "Add {count} required items", backupDependencyImpact: "Adds {add} items; {deleted} deleted items still need an individual choice; {missing} required items are unavailable.",
    backupSourceOptional: "This card can be restored without its source. Saved excerpts remain, but they cannot be rechecked until the source is available.",
    backupSourceAvailable: "Source is on this device", backupSourceIncluded: "Source is selected for import",
    backupSkipReasons: "Kept or skipped: {unselected} not selected, {same} identical or already restored, {dependency} waiting for required items, {blocked} unavailable.",
    backupWaitDependency: "Selected · required items missing", backupSourcePage: "Whole page", backupSourceSelection: "Selected text", backupFieldDeletedAt: "Deleted on",
    backupSiteDoubao: "Doubao", backupSiteQianwen: "Qianwen", backupSiteYuanbao: "Yuanbao", backupSiteChatglm: "Zhipu",
    backupAlreadyRestored: "Use the previously restored question",
    backupKindQuestion: "Question history", backupKindQuestionAnswer: "Saved answers", backupQuestionRemap: "Restore as a new history record. Select its saved answers separately.",
    backupFieldAnswers: "Answers", backupFieldSource: "Source", backupFieldSite: "Site", backupFieldExcerpt: "Excerpt", backupFieldSites: "Sites", backupFieldTier: "Tier", backupFieldId: "Record ID", backupFieldSchema: "Format version", backupFieldPreview: "Preview", backupFieldSynthesis: "Synthesis", backupFieldInstruction: "Instruction", backupFieldTime: "Saved time", backupFieldUrl: "Source URL", backupFieldKind: "Type", backupFieldCode: "Status code", backupFieldTruncated: "Truncated", backupFieldIndex: "Answer number", backupFieldFavorite: "Favorite", backupFieldFolder: "Folder ID", backupFieldTarget: "Content ID", backupFieldHash: "Content fingerprint",
    backupTitle: "Backup & restore", backupDescription: "Export your saved work, or review a backup before merging it into this device. Site sign-ins and credentials are excluded.",
    backupExport: "Export backup", backupImport: "Choose backup", backupExported: "Backup exported", backupReview: "Review backup", backupLocal: "On this device", backupIncoming: "In the backup",
    backupKeepLocal: "Keep local", backupUseIncoming: "Use backup", backupRestoreDeleted: "Restore this deleted item", backupInclude: "Import this item", backupSame: "Identical · no changes", backupNew: "New", backupConflict: "Conflict", backupDeleted: "Deleted locally", backupAll: "All items",
    backupSyncNotice: "Imported changes join normal Drive sync, including other devices. When disconnected, they wait until you reconnect. Items kept on this device remain unchanged.",
    backupSummary: "Import {count} selected items; keep or skip {skipped} items.", backupConfirmTitle: "Confirm merge", backupConfirm: "Confirm import", backupReviewSummary: "Review & import", backupEmpty: "No items in this view", backupNoLocal: "No active local version", backupCompleted: "Imported {count} items; skipped {skipped}.", backupFailed: "Could not complete the backup operation. Choose the file again to review the restore result.", backupStale: "Local data changed after this preview. Choose the backup again to review the latest differences.", backupInvalid: "This file is not a supported, valid PolyAsk backup.", backupTooLarge: "The backup exceeds the 32 MiB or 20,000-item limit.", backupApplying: "Importing…", backupDate: "Exported {date}", backupFolderRemap: "Restoring this folder creates a new folder identity. Select its memberships separately.", backupBlocked: "This association cannot be restored because its folder or content is unavailable. Restore the required items first, then preview again.",
    backupReuseFolder: "Use the previously restored folder", backupFolderReused: "This folder was restored before. Its restored copy and current edits will be kept.", backupSkipped: "Skip", backupDependency: "Also select the required folder and content to restore this link; otherwise it will be skipped.", backupKindTemplate: "Templates", backupKindGroup: "Site groups", backupKindWorkspace: "Sites & tier",
    backupKindHistory: "Questions", backupKindArchive: "Saved results", backupKindDecision: "Decision cards", backupKindFolder: "Folders", backupKindMembership: "Folder links", backupKindState: "Templates & preferences", backupDetails: "Business data", backupFieldValue: "Value"
  },
  zhCN: {
    backupCalculating: "正在核对所选条目…",
    backupYes: "是", backupNo: "否", backupNotSet: "未设置", backupUnknownValue: "未识别的值：{value}",
    backupChangedFields: "{count} 个变化字段", backupFullVersions: "完整版本", backupRawData: "原始数据",
    backupType: "条目类型", backupStatusFilter: "条目状态", backupConflictsOnly: "仅看冲突",
    backupVisibleScope: "当前显示 {count} 条 · 已选入导入 {selected} 条", backupSelectVisible: "对当前 {count} 条使用备份", backupClearVisible: "保留或跳过当前 {count} 条",
    backupBulkNotice: "批量操作只作用于当前显示范围。内容相同及不可用条目不纳入；已删除内容须逐条明确选择恢复。",
    backupRequiredEntities: "所需对象", backupDependencySelected: "已选择", backupDependencyMissing: "本机及这份备份均无可用对象", backupDependencyDeleted: "请逐条明确选择恢复", backupDependencyBlocked: "不可用",
    backupAddDependencies: "加入 {count} 个所需对象", backupDependencyImpact: "将加入 {add} 条；{deleted} 条已删除内容仍需逐条选择；{missing} 个所需对象不可用。",
    backupSourceOptional: "可以单独恢复这张卡片。已保存的摘录仍保留；来源不可用时，无法重新核对原文。",
    backupSourceAvailable: "来源已在本机", backupSourceIncluded: "来源已选入导入",
    backupSkipReasons: "保留或跳过：{unselected} 条未选择，{same} 条内容相同或已恢复，{dependency} 条缺少所需对象，{blocked} 条不可用。",
    backupWaitDependency: "已选择 · 缺少所需对象", backupSourcePage: "整页内容", backupSourceSelection: "选中文字", backupFieldDeletedAt: "删除时间",
    backupSiteDoubao: "豆包", backupSiteQianwen: "千问", backupSiteYuanbao: "元宝", backupSiteChatglm: "智谱",
    backupAlreadyRestored: "复用此前恢复的提问",
    backupKindQuestion: "提问历史", backupKindQuestionAnswer: "回答副本", backupQuestionRemap: "恢复为一条新的提问记录，请同时选择需要恢复的回答副本。",
    backupFieldAnswers: "回答", backupFieldSource: "来源", backupFieldSite: "站点", backupFieldExcerpt: "摘录", backupFieldSites: "站点范围", backupFieldTier: "档位", backupFieldId: "记录标识", backupFieldSchema: "格式版本", backupFieldPreview: "摘要", backupFieldSynthesis: "辅助综合", backupFieldInstruction: "指令", backupFieldTime: "保存时间", backupFieldUrl: "来源网址", backupFieldKind: "类型", backupFieldCode: "状态码", backupFieldTruncated: "是否截断", backupFieldIndex: "回答序号", backupFieldFavorite: "收藏", backupFieldFolder: "文件夹标识", backupFieldTarget: "内容标识", backupFieldHash: "内容指纹",
    backupTitle: "备份与恢复", backupDescription: "导出业务数据，或先核对备份再合并到本机。不包含站点登录及凭据。", backupExport: "导出备份", backupImport: "选择备份", backupExported: "备份已导出", backupReview: "核对备份", backupLocal: "本机版本", backupIncoming: "备份版本",
    backupKeepLocal: "保留本机", backupUseIncoming: "使用备份", backupRestoreDeleted: "恢复这条已删除内容", backupInclude: "导入此条", backupSame: "内容相同 · 无需改动", backupNew: "新增", backupConflict: "冲突", backupDeleted: "本机已删除", backupAll: "全部条目",
    backupSyncNotice: "导入的改动会参与正常 Drive 同步，并影响其他设备。未连接时等待重连后同步；选择保留本机的条目不作改动。", backupSummary: "将导入 {count} 条，保留或跳过 {skipped} 条。", backupConfirmTitle: "确认合并", backupConfirm: "确认导入", backupReviewSummary: "核对并导入", backupEmpty: "此分类没有条目", backupNoLocal: "本机无有效版本", backupCompleted: "已导入 {count} 条，跳过 {skipped} 条。", backupFailed: "备份操作未完成。请重新选择文件核对恢复结果。", backupStale: "预览后本机数据已变化。请重新选择备份，核对最新差异。", backupInvalid: "文件不是有效且受支持的 PolyAsk 备份。", backupTooLarge: "备份超过 32 MiB 或 20,000 条的限制。", backupApplying: "正在导入…", backupDate: "导出于 {date}", backupFolderRemap: "恢复此文件夹将创建新的文件夹身份；归属关系需单独选择恢复。", backupBlocked: "所需文件夹或内容不可用，暂不能恢复此归属。请先恢复所需内容，再重新预览。",
    backupReuseFolder: "复用此前恢复的文件夹", backupFolderReused: "此文件夹此前已恢复，将复用恢复后的文件夹并保留现有编辑。", backupSkipped: "跳过", backupDependency: "请同时选择恢复所需文件夹和内容，否则将跳过此归属关系。", backupKindTemplate: "自存模板", backupKindGroup: "站点分组", backupKindWorkspace: "站点与档位",
    backupKindHistory: "提问历史", backupKindArchive: "保存结果", backupKindDecision: "决策卡", backupKindFolder: "文件夹", backupKindMembership: "归属关系", backupKindState: "模板与偏好", backupDetails: "业务数据", backupFieldValue: "内容"
  },
  zhTW: {
    backupCalculating: "正在核對所選項目…",
    backupYes: "是", backupNo: "否", backupNotSet: "未設定", backupUnknownValue: "未辨識的值：{value}",
    backupChangedFields: "{count} 個變更欄位", backupFullVersions: "完整版本", backupRawData: "原始資料",
    backupType: "項目類型", backupStatusFilter: "項目狀態", backupConflictsOnly: "只看衝突",
    backupVisibleScope: "目前顯示 {count} 筆 · 已選入匯入 {selected} 筆", backupSelectVisible: "對目前 {count} 筆使用備份", backupClearVisible: "保留或略過目前 {count} 筆",
    backupBulkNotice: "批次操作只作用於目前顯示範圍。內容相同及無法使用的項目不納入；已刪除內容須逐筆明確選擇還原。",
    backupRequiredEntities: "所需物件", backupDependencySelected: "已選擇", backupDependencyMissing: "本機及這份備份均無可用物件", backupDependencyDeleted: "請逐筆明確選擇還原", backupDependencyBlocked: "無法使用",
    backupAddDependencies: "加入 {count} 個所需物件", backupDependencyImpact: "將加入 {add} 筆；{deleted} 筆已刪除內容仍需逐筆選擇；{missing} 個所需物件無法使用。",
    backupSourceOptional: "可以單獨還原這張卡片。已儲存的摘錄仍保留；來源無法使用時，無法重新核對原文。",
    backupSourceAvailable: "來源已在本機", backupSourceIncluded: "來源已選入匯入",
    backupSkipReasons: "保留或略過：{unselected} 筆未選擇，{same} 筆內容相同或已還原，{dependency} 筆缺少所需物件，{blocked} 筆無法使用。",
    backupWaitDependency: "已選擇 · 缺少所需物件", backupSourcePage: "整頁內容", backupSourceSelection: "選取文字", backupFieldDeletedAt: "刪除時間",
    backupSiteDoubao: "豆包", backupSiteQianwen: "千問", backupSiteYuanbao: "元寶", backupSiteChatglm: "智譜",
    backupAlreadyRestored: "沿用先前還原的提問",
    backupKindQuestion: "提問歷史", backupKindQuestionAnswer: "回答副本", backupQuestionRemap: "恢復為一筆新的提問記錄，請同時選擇需要恢復的回答副本。",
    backupFieldAnswers: "回答", backupFieldSource: "來源", backupFieldSite: "網站", backupFieldExcerpt: "摘錄", backupFieldSites: "網站範圍", backupFieldTier: "檔位", backupFieldId: "紀錄識別碼", backupFieldSchema: "格式版本", backupFieldPreview: "摘要", backupFieldSynthesis: "輔助綜合", backupFieldInstruction: "指令", backupFieldTime: "儲存時間", backupFieldUrl: "來源網址", backupFieldKind: "類型", backupFieldCode: "狀態碼", backupFieldTruncated: "是否截斷", backupFieldIndex: "回答編號", backupFieldFavorite: "收藏", backupFieldFolder: "資料夾識別碼", backupFieldTarget: "內容識別碼", backupFieldHash: "內容指紋",
    backupTitle: "備份與還原", backupDescription: "匯出業務資料，或先核對備份再合併到本機。不包含網站登入及憑證。", backupExport: "匯出備份", backupImport: "選擇備份", backupExported: "備份已匯出", backupReview: "核對備份", backupLocal: "本機版本", backupIncoming: "備份版本",
    backupKeepLocal: "保留本機", backupUseIncoming: "使用備份", backupRestoreDeleted: "還原這筆已刪除內容", backupInclude: "匯入此筆", backupSame: "內容相同 · 無須變更", backupNew: "新增", backupConflict: "衝突", backupDeleted: "本機已刪除", backupAll: "全部項目",
    backupSyncNotice: "匯入的變更會參與正常 Drive 同步，並影響其他裝置。未連線時等待重新連線後同步；選擇保留本機的項目不作變更。", backupSummary: "將匯入 {count} 筆，保留或略過 {skipped} 筆。", backupConfirmTitle: "確認合併", backupConfirm: "確認匯入", backupReviewSummary: "核對並匯入", backupEmpty: "此分類沒有項目", backupNoLocal: "本機無有效版本", backupCompleted: "已匯入 {count} 筆，略過 {skipped} 筆。", backupFailed: "備份操作未完成。請重新選擇檔案核對還原結果。", backupStale: "預覽後本機資料已變更。請重新選擇備份，核對最新差異。", backupInvalid: "檔案不是有效且受支援的 PolyAsk 備份。", backupTooLarge: "備份超過 32 MiB 或 20,000 筆的限制。", backupApplying: "正在匯入…", backupDate: "匯出於 {date}", backupFolderRemap: "還原此資料夾將建立新的資料夾身分；歸屬關係需另行選擇還原。", backupBlocked: "所需資料夾或內容無法使用，暫不能還原此歸屬。請先還原所需內容，再重新預覽。",
    backupReuseFolder: "沿用先前還原的資料夾", backupFolderReused: "此資料夾先前已還原，將沿用還原後的資料夾並保留現有編輯。", backupSkipped: "略過", backupDependency: "請同時選擇還原所需資料夾和內容，否則將略過此歸屬關係。", backupKindTemplate: "自存範本", backupKindGroup: "網站分組", backupKindWorkspace: "網站與檔位",
    backupKindHistory: "提問歷史", backupKindArchive: "儲存結果", backupKindDecision: "決策卡", backupKindFolder: "資料夾", backupKindMembership: "歸屬關係", backupKindState: "範本與偏好", backupDetails: "業務資料", backupFieldValue: "內容"
  }
} as const;
