export const BACKUP_COPY = {
  en: {
    backupKindQuestion: "Question history", backupKindQuestionAnswer: "Saved answers", backupQuestionRemap: "Restore as a new history record. Select its saved answers separately.",
    backupFieldAnswers: "Answers", backupFieldSource: "Source", backupFieldSite: "Site", backupFieldExcerpt: "Excerpt", backupFieldSites: "Sites", backupFieldTier: "Tier", backupFieldId: "Record ID", backupFieldSchema: "Format version", backupFieldPreview: "Preview", backupFieldSynthesis: "Synthesis", backupFieldInstruction: "Instruction", backupFieldTime: "Saved time", backupFieldUrl: "Source URL", backupFieldKind: "Type", backupFieldCode: "Status code", backupFieldTruncated: "Truncated", backupFieldIndex: "Answer number", backupFieldFavorite: "Favorite", backupFieldFolder: "Folder ID", backupFieldTarget: "Content ID", backupFieldHash: "Content fingerprint",
    backupTitle: "Backup & restore", backupDescription: "Export your saved work, or review a backup before merging it into this device. Site sign-ins and credentials are excluded.",
    backupExport: "Export backup", backupImport: "Choose backup", backupExported: "Backup exported", backupReview: "Review backup", backupLocal: "On this device", backupIncoming: "In the backup",
    backupKeepLocal: "Keep local", backupUseIncoming: "Use backup", backupRestoreDeleted: "Restore this deleted item", backupInclude: "Import this item", backupSame: "Identical · no changes", backupNew: "New", backupConflict: "Conflict", backupDeleted: "Deleted locally", backupAll: "All items",
    backupSyncNotice: "Imported changes join normal Drive sync, including other devices. When disconnected, they wait until you reconnect. Items kept on this device remain unchanged.",
    backupSummary: "Import {count} selected items; keep or skip {skipped} items.", backupConfirmTitle: "Confirm merge", backupConfirm: "Confirm import", backupReviewSummary: "Review & import", backupEmpty: "No items in this view", backupNoLocal: "No active local version", backupCompleted: "Imported {count} items; skipped {skipped}.", backupFailed: "Could not complete the backup operation. Choose the file again to review the restore result.", backupStale: "Local data changed after this preview. Choose the backup again to review the latest differences.", backupInvalid: "This file is not a supported, valid PolyAsk backup.", backupTooLarge: "The backup exceeds the 32 MiB or 20,000-item limit.", backupApplying: "Importing…", backupDate: "Exported {date}", backupFolderRemap: "Restoring this folder creates a new folder identity. Select its memberships separately.", backupBlocked: "This association cannot be restored because its folder or content is unavailable. Restore the required items first, then preview again.",
    backupReuseFolder: "Use the previously restored folder", backupFolderReused: "This folder was restored before. Its restored copy and current edits will be kept.", backupSkipped: "Skip", backupDependency: "Also select the required folder and content to restore this link; otherwise it will be skipped.", backupKindTemplate: "Templates", backupKindGroup: "Site groups", backupKindWorkspace: "Sites & tier",
    backupKindHistory: "Questions", backupKindArchive: "Saved results", backupKindDecision: "Decision cards", backupKindFolder: "Folders", backupKindMembership: "Folder links", backupKindState: "Templates & preferences", backupDetails: "Business data", backupFieldValue: "Value"
  },
  zhCN: {
    backupKindQuestion: "提问历史", backupKindQuestionAnswer: "回答副本", backupQuestionRemap: "恢复为一条新的提问记录，请同时选择需要恢复的回答副本。",
    backupFieldAnswers: "回答", backupFieldSource: "来源", backupFieldSite: "站点", backupFieldExcerpt: "摘录", backupFieldSites: "站点范围", backupFieldTier: "档位", backupFieldId: "记录标识", backupFieldSchema: "格式版本", backupFieldPreview: "摘要", backupFieldSynthesis: "辅助综合", backupFieldInstruction: "指令", backupFieldTime: "保存时间", backupFieldUrl: "来源网址", backupFieldKind: "类型", backupFieldCode: "状态码", backupFieldTruncated: "是否截断", backupFieldIndex: "回答序号", backupFieldFavorite: "收藏", backupFieldFolder: "文件夹标识", backupFieldTarget: "内容标识", backupFieldHash: "内容指纹",
    backupTitle: "备份与恢复", backupDescription: "导出业务数据，或先核对备份再合并到本机。不包含站点登录及凭据。", backupExport: "导出备份", backupImport: "选择备份", backupExported: "备份已导出", backupReview: "核对备份", backupLocal: "本机版本", backupIncoming: "备份版本",
    backupKeepLocal: "保留本机", backupUseIncoming: "使用备份", backupRestoreDeleted: "恢复这条已删除内容", backupInclude: "导入此条", backupSame: "内容相同 · 无需改动", backupNew: "新增", backupConflict: "冲突", backupDeleted: "本机已删除", backupAll: "全部条目",
    backupSyncNotice: "导入的改动会参与正常 Drive 同步，并影响其他设备。未连接时等待重连后同步；选择保留本机的条目不作改动。", backupSummary: "将导入 {count} 条，保留或跳过 {skipped} 条。", backupConfirmTitle: "确认合并", backupConfirm: "确认导入", backupReviewSummary: "核对并导入", backupEmpty: "此分类没有条目", backupNoLocal: "本机无有效版本", backupCompleted: "已导入 {count} 条，跳过 {skipped} 条。", backupFailed: "备份操作未完成。请重新选择文件核对恢复结果。", backupStale: "预览后本机数据已变化。请重新选择备份，核对最新差异。", backupInvalid: "文件不是有效且受支持的 PolyAsk 备份。", backupTooLarge: "备份超过 32 MiB 或 20,000 条的限制。", backupApplying: "正在导入…", backupDate: "导出于 {date}", backupFolderRemap: "恢复此文件夹将创建新的文件夹身份；归属关系需单独选择恢复。", backupBlocked: "所需文件夹或内容不可用，暂不能恢复此归属。请先恢复所需内容，再重新预览。",
    backupReuseFolder: "复用此前恢复的文件夹", backupFolderReused: "此文件夹此前已恢复，将复用恢复后的文件夹并保留现有编辑。", backupSkipped: "跳过", backupDependency: "请同时选择恢复所需文件夹和内容，否则将跳过此归属关系。", backupKindTemplate: "自存模板", backupKindGroup: "站点分组", backupKindWorkspace: "站点与档位",
    backupKindHistory: "提问历史", backupKindArchive: "保存结果", backupKindDecision: "决策卡", backupKindFolder: "文件夹", backupKindMembership: "归属关系", backupKindState: "模板与偏好", backupDetails: "业务数据", backupFieldValue: "内容"
  },
  zhTW: {
    backupKindQuestion: "提問歷史", backupKindQuestionAnswer: "回答副本", backupQuestionRemap: "恢復為一筆新的提問記錄，請同時選擇需要恢復的回答副本。",
    backupFieldAnswers: "回答", backupFieldSource: "來源", backupFieldSite: "網站", backupFieldExcerpt: "摘錄", backupFieldSites: "網站範圍", backupFieldTier: "檔位", backupFieldId: "紀錄識別碼", backupFieldSchema: "格式版本", backupFieldPreview: "摘要", backupFieldSynthesis: "輔助綜合", backupFieldInstruction: "指令", backupFieldTime: "儲存時間", backupFieldUrl: "來源網址", backupFieldKind: "類型", backupFieldCode: "狀態碼", backupFieldTruncated: "是否截斷", backupFieldIndex: "回答編號", backupFieldFavorite: "收藏", backupFieldFolder: "資料夾識別碼", backupFieldTarget: "內容識別碼", backupFieldHash: "內容指紋",
    backupTitle: "備份與還原", backupDescription: "匯出業務資料，或先核對備份再合併到本機。不包含網站登入及憑證。", backupExport: "匯出備份", backupImport: "選擇備份", backupExported: "備份已匯出", backupReview: "核對備份", backupLocal: "本機版本", backupIncoming: "備份版本",
    backupKeepLocal: "保留本機", backupUseIncoming: "使用備份", backupRestoreDeleted: "還原這筆已刪除內容", backupInclude: "匯入此筆", backupSame: "內容相同 · 無須變更", backupNew: "新增", backupConflict: "衝突", backupDeleted: "本機已刪除", backupAll: "全部項目",
    backupSyncNotice: "匯入的變更會參與正常 Drive 同步，並影響其他裝置。未連線時等待重新連線後同步；選擇保留本機的項目不作變更。", backupSummary: "將匯入 {count} 筆，保留或略過 {skipped} 筆。", backupConfirmTitle: "確認合併", backupConfirm: "確認匯入", backupReviewSummary: "核對並匯入", backupEmpty: "此分類沒有項目", backupNoLocal: "本機無有效版本", backupCompleted: "已匯入 {count} 筆，略過 {skipped} 筆。", backupFailed: "備份操作未完成。請重新選擇檔案核對還原結果。", backupStale: "預覽後本機資料已變更。請重新選擇備份，核對最新差異。", backupInvalid: "檔案不是有效且受支援的 PolyAsk 備份。", backupTooLarge: "備份超過 32 MiB 或 20,000 筆的限制。", backupApplying: "正在匯入…", backupDate: "匯出於 {date}", backupFolderRemap: "還原此資料夾將建立新的資料夾身分；歸屬關係需另行選擇還原。", backupBlocked: "所需資料夾或內容無法使用，暫不能還原此歸屬。請先還原所需內容，再重新預覽。",
    backupReuseFolder: "沿用先前還原的資料夾", backupFolderReused: "此資料夾先前已還原，將沿用還原後的資料夾並保留現有編輯。", backupSkipped: "略過", backupDependency: "請同時選擇還原所需資料夾和內容，否則將略過此歸屬關係。", backupKindTemplate: "自存範本", backupKindGroup: "網站分組", backupKindWorkspace: "網站與檔位",
    backupKindHistory: "提問歷史", backupKindArchive: "儲存結果", backupKindDecision: "決策卡", backupKindFolder: "資料夾", backupKindMembership: "歸屬關係", backupKindState: "範本與偏好", backupDetails: "業務資料", backupFieldValue: "內容"
  }
} as const;
