export const BROADCAST_RETRY_COPY = {
  en: {
    retryInspectionPending: 'Opening the requested site…',
    retrySiteClosed: '{site} is not open. Select it in the site list before inspecting it; this also adds it to future broadcasts. Reopening does not prove it was not sent.',
    retryReviewAction: 'Review {count} uncertain sites',
    retryReviewCompact: 'Review',
    retryReviewTitle: 'Check before resending',
    retryReviewDescription: 'PolyAsk could not confirm submission. The original question may already be on these sites. Inspect each site before choosing to resend; resending may create a duplicate question.',
    retryReviewChoice: 'I checked {site} and choose to resend the original question',
    retryInspectSite: 'Inspect {site}',
    retryReviewConfirm: 'Resend to {count} checked sites',
    retryReviewResolved: 'These submissions are now confirmed. No resend is needed.',
    retryReviewSite: 'Review submission to {site}',
  },
  zhCN: {
    retryInspectionPending: '正在定位本站页面…',
    retrySiteClosed: '{site} 当前未打开。请先在站点列表重新选择后查看；重新选择也会加入后续群发范围。重新打开不能证明此前未发送。',
    retryReviewAction: '核对 {count} 个未确认站点',
    retryReviewCompact: '待核对',
    retryReviewTitle: '重发前核对',
    retryReviewDescription: 'PolyAsk 尚未确认提交结果，原问题可能已经发送。请先逐站查看，再选择是否重发；重发可能造成重复提问。',
    retryReviewChoice: '我已查看 {site}，决定重发原问题',
    retryInspectSite: '查看 {site}',
    retryReviewConfirm: '向勾选的 {count} 个站点重发',
    retryReviewResolved: '这些站点的提交已确认，无需重发。',
    retryReviewSite: '核对 {site} 的提交结果',
  },
  zhTW: {
    retryInspectionPending: '正在定位本站頁面…',
    retrySiteClosed: '{site} 目前未開啟。請先在網站列表重新選取後查看；重新選取也會加入後續群發範圍。重新開啟不能證明先前未傳送。',
    retryReviewAction: '核對 {count} 個未確認網站',
    retryReviewCompact: '待核對',
    retryReviewTitle: '重新傳送前核對',
    retryReviewDescription: 'PolyAsk 尚未確認提交結果，原問題可能已經傳送。請先逐一查看網站，再選擇是否重新傳送；重新傳送可能造成重複提問。',
    retryReviewChoice: '我已查看 {site}，決定重新傳送原問題',
    retryInspectSite: '查看 {site}',
    retryReviewConfirm: '向勾選的 {count} 個網站重新傳送',
    retryReviewResolved: '這些網站的提交已確認，無需重新傳送。',
    retryReviewSite: '核對 {site} 的提交結果',
  }
} as const;
