export const COMPARISON_COPY = {
  en: {
    comparisonExpand: 'Expand comparison', comparisonBrowse: 'Return to browsing',
    synthesisNewConversation: 'A new conversation will open at the selected site.',
    synthesisPayloadCount: '{count} characters', synthesisCopyPayload: 'Copy complete contents',
    synthesisPayloadCopied: 'Complete contents copied.', synthesisPayloadCopyFailed: 'Could not copy complete contents.',
    excerptSelectOriginal: 'Select original excerpt', excerptReviewOriginal: 'Review saved original',
    excerptOriginalHint: 'Select a continuous passage in the saved original. Formatting and repeated text need an exact range.',
    excerptOriginal: 'Saved original text', excerptUseSelection: 'Use this excerpt', excerptUseEvidence: 'Use as evidence',
    excerptFollowUp: 'Follow up on excerpt', excerptManualCompare: 'Add to manual comparison', excerptClear: 'Clear selection',
    excerptEvidenceLimit: 'Evidence and manual comparison allow up to 4,000 characters per source. Follow-up uses the complete payload limit.',
    synthesisSourceVersionChanged: 'The saved source changed. Reload and review it before sending.',
    excerptSourceMissing: 'This saved source is no longer available.', excerptSourceInvalid: 'This excerpt no longer matches its saved source. Select it again.',
    excerptReplaceTitle: 'Replace the previous excerpt?', excerptPrevious: 'Previous excerpt', excerptSelected: 'New selected excerpt', excerptReplaceMessage: 'Your target, model tier and question will be kept. Only the quoted excerpt will change.', excerptReplaceConfirm: 'Use selected excerpt',
    analysisTitle: 'Supplementary analysis', analysisSaved: 'Saved supplementary analysis',
    analysisWaiting: 'Submitted. Waiting for the target answer; not saved.', analysisReview: 'Collected. Review before saving.',
    analysisOriginalRequest: 'Request at the time', analysisRequestMissing: 'The request was not recorded.', analysisCollectAgain: 'Collect again',
    analysisSourceChanged: 'The saved source changed after submission. Review the returned answer against the material used at that time.',
    synthesisReviewSource: 'Reload and review source', synthesisUseReviewed: 'Use reviewed sources',
    synthesisReviewHint: 'Review the complete saved material. Your target, model tier, question and excerpt are retained.',
    manualTitle: 'Manual comparison', manualHint: 'Classify quotes and write your own notes. Literal differences do not prove disagreement. Notes stay in this session; form a decision to save them. Each source can have one continuous excerpt.',
    manualConclusion: 'Conclusions', manualEvidence: 'Evidence', manualConditions: 'Conditions', manualCost: 'Costs',
    manualEmpty: 'Not organized', manualExcerpt: 'Selected source excerpt', manualJudgment: 'My judgment', manualNextStep: 'My next verification step',
    manualFormDecision: 'Form decision draft', manualSourceChanged: 'Saved sources changed. Select and review the affected quotes again; your notes are retained.',
    manualReplaceQuote: 'This source already has an excerpt. Replace it with the newly selected continuous passage? Your manual notes will be kept.', manualRemoveExcerpt: 'Remove excerpt'
  },
  'zh-CN': {
    comparisonExpand: '展开比较', comparisonBrowse: '返回浏览',
    synthesisNewConversation: '将在所选站点打开新会话。',
    synthesisPayloadCount: '{count} 个字符', synthesisCopyPayload: '复制完整内容',
    synthesisPayloadCopied: '完整内容已复制。', synthesisPayloadCopyFailed: '完整内容复制失败。',
    excerptSelectOriginal: '选择原文摘录', excerptReviewOriginal: '核对保存原文',
    excerptOriginalHint: '请在保存原文中选择连续片段。格式跨节点或重复文本需要明确原文范围。',
    excerptOriginal: '保存的原文', excerptUseSelection: '使用这段摘录', excerptUseEvidence: '摘为证据',
    excerptFollowUp: '追问这段', excerptManualCompare: '加入人工对照', excerptClear: '清除选文',
    excerptEvidenceLimit: '证据和人工对照每份来源最多 4,000 字。追问仍按完整发送内容的上限校验。',
    synthesisSourceVersionChanged: '保存来源已变更，请重新载入并核对后再发送。',
    excerptSourceMissing: '这份保存来源已不可用。', excerptSourceInvalid: '摘录已无法逐字对应保存来源，请重新选择。',
    excerptReplaceTitle: '替换之前的摘录？', excerptPrevious: '之前的摘录', excerptSelected: '新选的摘录', excerptReplaceMessage: '将保留目标、档位和已写追问，只替换引用的摘录。', excerptReplaceConfirm: '使用新选摘录',
    analysisTitle: '补充分析', analysisSaved: '已保存补充分析',
    analysisWaiting: '已提交，等待目标回答，尚未保存。', analysisReview: '已取回，请核对后再保存。',
    analysisOriginalRequest: '当时要求', analysisRequestMissing: '当时要求未记录。', analysisCollectAgain: '重新取回',
    analysisSourceChanged: '提交后保存来源已变更，请将取回的回答与当时使用的材料核对。',
    synthesisReviewSource: '重新载入并核对来源', synthesisUseReviewed: '使用已核对来源',
    synthesisReviewHint: '请核对完整的保存材料。目标、档位、追问和摘录会保留。',
    manualTitle: '人工对照', manualHint: '由你分类摘录并记录判断。字面不同不代表意见相反。笔记仅保留在本次会话，形成决策后才能保存；每份来源保留一段连续摘录。',
    manualConclusion: '结论', manualEvidence: '依据', manualConditions: '条件', manualCost: '成本',
    manualEmpty: '未整理', manualExcerpt: '所选来源摘录', manualJudgment: '我的判断', manualNextStep: '下一步核验行动',
    manualFormDecision: '形成决策草稿', manualSourceChanged: '保存来源已变更，请重新选择并核对受影响的摘录；人工笔记会保留。',
    manualReplaceQuote: '这份来源已有摘录，是否替换为新选的连续片段？人工笔记会保留。', manualRemoveExcerpt: '移除摘录'
  },
  'zh-TW': {
    comparisonExpand: '展開比較', comparisonBrowse: '返回瀏覽',
    synthesisNewConversation: '將在所選站點開啟新對話。',
    synthesisPayloadCount: '{count} 個字元', synthesisCopyPayload: '複製完整內容',
    synthesisPayloadCopied: '完整內容已複製。', synthesisPayloadCopyFailed: '完整內容複製失敗。',
    excerptSelectOriginal: '選擇原文摘錄', excerptReviewOriginal: '核對儲存原文',
    excerptOriginalHint: '請在儲存原文中選擇連續片段。跨格式節點或重複文字需要明確原文範圍。',
    excerptOriginal: '儲存的原文', excerptUseSelection: '使用這段摘錄', excerptUseEvidence: '摘為證據',
    excerptFollowUp: '追問這段', excerptManualCompare: '加入人工對照', excerptClear: '清除選文',
    excerptEvidenceLimit: '證據和人工對照每份來源最多 4,000 字。追問仍按完整傳送內容的上限檢查。',
    synthesisSourceVersionChanged: '儲存來源已變更，請重新載入並核對後再傳送。',
    excerptSourceMissing: '這份儲存來源已不可用。', excerptSourceInvalid: '摘錄已無法逐字對應儲存來源，請重新選擇。',
    excerptReplaceTitle: '取代之前的摘錄？', excerptPrevious: '之前的摘錄', excerptSelected: '新選的摘錄', excerptReplaceMessage: '將保留目標、檔位和已寫追問，只取代引用的摘錄。', excerptReplaceConfirm: '使用新選摘錄',
    analysisTitle: '補充分析', analysisSaved: '已儲存補充分析',
    analysisWaiting: '已提交，等待目標回答，尚未儲存。', analysisReview: '已取回，請核對後再儲存。',
    analysisOriginalRequest: '當時要求', analysisRequestMissing: '當時要求未記錄。', analysisCollectAgain: '重新取回',
    analysisSourceChanged: '提交後儲存來源已變更，請將取回的回答與當時使用的材料核對。',
    synthesisReviewSource: '重新載入並核對來源', synthesisUseReviewed: '使用已核對來源',
    synthesisReviewHint: '請核對完整的儲存材料。目標、檔位、追問和摘錄會保留。',
    manualTitle: '人工對照', manualHint: '由你分類摘錄並記錄判斷。字面不同不代表意見相反。筆記只保留在本次會話，形成決策後才能儲存；每份來源保留一段連續摘錄。',
    manualConclusion: '結論', manualEvidence: '依據', manualConditions: '條件', manualCost: '成本',
    manualEmpty: '未整理', manualExcerpt: '所選來源摘錄', manualJudgment: '我的判斷', manualNextStep: '下一步核驗行動',
    manualFormDecision: '形成決策草稿', manualSourceChanged: '儲存來源已變更，請重新選擇並核對受影響的摘錄；人工筆記會保留。',
    manualReplaceQuote: '這份來源已有摘錄，是否取代為新選的連續片段？人工筆記會保留。', manualRemoveExcerpt: '移除摘錄'
  }
} as const;
