import { TASK_FOLDER_COPY } from "./task-folder-copy";
import { DECISION_COPY } from "./decision-copy";
import { ARCHIVE_COPY } from "./archive-copy";
import { COMMAND_COPY } from "./command-copy";
import { DATA_ADMIN_COPY } from "./data-admin-copy";
import { resolveLocale, type DesktopLocale } from "./locale";
import { PROMPT_LIBRARY_COPY } from "./prompt-library-copy";
import { PRODUCTIVITY_COPY } from "./productivity-copy";
import { SYNC_COPY } from "./sync-copy";
import { SYNTHESIS_COPY } from "./synthesis-copy";
import { WORKSPACE_COPY } from "./workspace-copy";

export const COPY = {
  en: {
    ...ARCHIVE_COPY.en,
    ...DECISION_COPY.en,
    ...TASK_FOLDER_COPY.en,
    ...COMMAND_COPY.en,
    ...PROMPT_LIBRARY_COPY.en,
    ...PRODUCTIVITY_COPY.en,
    ...SYNC_COPY.en,
    ...DATA_ADMIN_COPY.en,
    ...SYNTHESIS_COPY.en,
    ...WORKSPACE_COPY.en,
    appTitle: "PolyAsk · AI Answers",
    startupFailedTitle: "PolyAsk could not start",
    startupFailedMessage: "Restart PolyAsk. If the problem continues, attach the diagnostic log when reporting it.",
    shellLoading: "Starting PolyAsk…",
    shellLoadFailed: "PolyAsk could not load the workspace.",
    retryShellLoad: "Try again",
    displayPreferencesFailed: "Could not apply display preferences",
    layoutAutoFocus: "Switched to Focus to keep answers readable. Enlarge the window to restore Overview.",
    overview: "Overview",
    focus: "Focus",
    layoutLabel: "View layout",
    sitePages: "Site pages",
    sitePageLabel: "Page {page}, sites {range}",
    sitePageSending: "{count} sending",
    sitePageGenerating: "{count} responding",
    sitePageComplete: "{count} complete",
    sitePageFailed: "{count} failed",
    sitePageChanged: "Showing page {page} of {total}",
    nextPageMenu: "Next site page",
    previousPageMenu: "Previous site page",
    sitePageMenu: "Show site page {page}",
    addImages: "Add images",
    manageImages: "Manage {count} images",
    closeImages: "Close image list",
    closeSettings: "Close settings",
    appVersion: "PolyAsk {version} · {mode}",
    installedMode: "Installed",
    portableMode: "Portable",
    portableImportTitle: "Import existing PolyAsk data?",
    portableImportMessage: "PolyAsk found existing settings and site sign-ins. Copy them into this portable version? The originals will stay where they are.",
    portableImport: "Import data",
    portableStartFresh: "Start fresh",
    portableImportFailedTitle: "Could not import existing data",
    portableImportFailedMessage: "Exit every PolyAsk process, then reopen this portable copy and try again. Your existing settings and sign-ins are still in their original location.",
    portableLegacyInUseTitle: "Close PolyAsk before continuing",
    portableLegacyInUseMessage: "Another PolyAsk process is using the existing data. Exit it completely, then reopen App\\polyask-desktop.exe. Your settings and sign-ins are still in their original location.",
    portableDataConflictTitle: "PolyAsk Data was left untouched",
    portableDataConflictMessage: "PolyAsk Data contains files that PolyAsk cannot verify, so it was not replaced. Move or back up those files, then reopen App\\polyask-desktop.exe.",
    portableStorageFailedTitle: "Portable data folder is unavailable",
    portableStorageFailedMessage: "Move PolyAsk Portable to a folder you can write to, then open it again.",
    replaceImages: "Replace images",
    removeImage: "Remove {name}",
    imagesReady: "{count} images selected",
    imageCountError: "Choose 1 to 4 images",
    imageTypeError: "Only PNG and JPEG images are supported",
    imageSizeError: "Images must total 10 MiB or less",
    imageInvalid: "An image could not be read safely",
    imagesBusy: "Broadcasting is in progress; images can't be added right now",
    imageUnsupported: "Image broadcasts are not supported by {sites}; adjust site scope",
    adjustImageScope: "Adjust site scope: {count} unsupported",
    imagePayloadInvalid: "Image payload is invalid",
    attachmentUnsupported: "This site does not support image broadcasts",
    attachmentFailed: "Could not attach images",
    attachmentTimedOut: "Timed out waiting for image attachments",
    attachmentActionRequired: "Finish the image attachment action on this site",
    broadcastLabel: "Broadcast prompt",
    promptPlaceholder: "Ask one question across the selected AI sites…",
    promptLabel: "Prompt",
    tierLabel: "Response mode",
    followSite: "Use site setting",
    fast: "Fast",
    think: "Deep thinking",
    cancel: "Cancel",
    cancelling: "Cancelling…",
    send: "Send",
    sendToOneSite: "Send to {count} site",
    sendToSites: "Send to {count} sites",
    siteViews: "AI site views",
    selectSite: "Send to {site}",
    focusSite: "Focus {site}",
    reloadSite: "Reload {site}",
    loading: "Loading",
    ready: "Ready",
    sending: "Sending",
    submitted: "Sent",
    generating: "Answering",
    answerComplete: "Answer complete",
    submittedWithWarning: "Sent with warning",
    tierUnconfirmed: "Sent; response mode not confirmed",
    composerNotFound: "Prompt box not found",
    siteNotReady: "Site not ready",
    submitUnconfirmed: "Whether it was sent is unconfirmed",
    timedOut: "Timed out",
    cancelledStatus: "Cancelled",
    injectFailed: "Could not fill prompt",
    siteUnavailable: "Site view unavailable",
    answerTruncated: "This answer was too long and has been truncated",
    loadFailed: "Page failed to load",
    invalidResponse: "Site returned an unexpected response",
    siteError: "Site script failed",
    adapterUnavailable: "Site script not loaded",
    operationBusy: "Another send or new session is in progress. Wait for it to finish or cancel it.",
    failed: "Failed",
    crashed: "Stopped",
    fileMenu: "File",
    editMenu: "Edit",
    viewMenu: "View",
    windowMenu: "Window",
    focusPromptMenu: "Focus prompt input",
    nextSiteMenu: "Focus next site",
    previousSiteMenu: "Focus previous site",
    siteBack: "Go back in {site}",
    siteBackMenu: "Back in site",
    siteForwardMenu: "Forward in site",
    densityMenu: "Interface density",
    compactDensity: "Compact",
    comfortableDensity: "Comfortable",
    siteScaleMenu: "Site scale",
    fitSiteScale: "Fit (90%)",
    actualSiteScale: "Actual size (100%)",
    commandPalette: "Command palette",
    sitesAndGroups: "Sites & groups",
    siteHealth: "Site status",
    showPageOne: "Show site page 1",
    showPageTwo: "Show site page 2",
    showPageThree: "Show site page 3",
    chooseThinkMode: "Use deep thinking",
    chooseFastMode: "Use fast responses",
    retryFailedCommand: "Retry failed sites",
    openDriveDiagnostics: "Open Drive diagnostics",
    keyboardShortcuts: "Keyboard shortcuts",
    gettingStarted: "Getting started",
    guideIntro: "Try one question with two familiar sites. This guide never changes your site selection or sends a question automatically.",
    guideChooseTitle: "Choose where to ask",
    guideChooseBody: "Open Sites and groups and choose the sites you want. Start with two; add others whenever you need them.",
    guideLoginTitle: "Sign in on each site",
    guideLoginBody: "Close this guide to sign in directly on each site's page. Site status provides read-only checks; an unknown status does not necessarily mean you are signed out.",
    guideAskTitle: "Ask once",
    guideAskBody: "Enter your question, check the selected sites and response mode, then press Send. Sent does not mean the answer is complete. If submission is uncertain, check the site before manually retrying to avoid a duplicate question.",
    guideCompareTitle: "Capture and compare",
    guideCompareBody: "Once the answers you need are ready, capture a snapshot in the result library and compare two answers. Capture reads the current pages; review the content and any truncation warnings. Exact paragraph matches do not establish factual accuracy.",
    guideReturnHint: "Open this guide again from More actions or search Getting started in the command palette (F1). Closing it returns to your sites and preserves your draft.",
    nextUnfinished: "Go to next unfinished site",
    nextFailed: "Go to next failed site",
    checkForUpdates: "Check for updates"
  },
  zhCN: {
    ...ARCHIVE_COPY.zhCN,
    ...DECISION_COPY.zhCN,
    ...TASK_FOLDER_COPY.zhCN,
    ...COMMAND_COPY.zhCN,
    ...PROMPT_LIBRARY_COPY.zhCN,
    ...PRODUCTIVITY_COPY.zhCN,
    ...SYNC_COPY.zhCN,
    ...DATA_ADMIN_COPY.zhCN,
    ...SYNTHESIS_COPY.zhCN,
    ...WORKSPACE_COPY.zhCN,
    appTitle: "PolyAsk · AI 众答",
    startupFailedTitle: "PolyAsk 无法启动",
    startupFailedMessage: "请重启 PolyAsk。若问题仍然存在，请在反馈时附上诊断日志。",
    shellLoading: "正在启动 PolyAsk……",
    shellLoadFailed: "PolyAsk 工作区加载失败。",
    retryShellLoad: "重试",
    displayPreferencesFailed: "无法应用显示偏好设置",
    layoutAutoFocus: "窗口空间不足，已切为聚焦以保持可读性；放大窗口可恢复总览。",
    overview: "总览",
    focus: "聚焦",
    layoutLabel: "视图布局",
    sitePages: "站点分页",
    sitePageLabel: "第 {page} 页，站点 {range}",
    sitePageSending: "{count} 个发送中",
    sitePageGenerating: "{count} 个正在回答",
    sitePageComplete: "{count} 个已完成",
    sitePageFailed: "{count} 个失败",
    sitePageChanged: "正在显示第 {page} 页，共 {total} 页",
    nextPageMenu: "下一组站点",
    previousPageMenu: "上一组站点",
    sitePageMenu: "显示第 {page} 组站点",
    addImages: "添加图片",
    manageImages: "管理 {count} 张图片",
    closeImages: "关闭图片列表",
    closeSettings: "关闭设置",
    appVersion: "PolyAsk {version} · {mode}",
    installedMode: "安装版",
    portableMode: "便携版",
    portableImportTitle: "是否导入现有 PolyAsk 数据？",
    portableImportMessage: "检测到现有 PolyAsk 的设置和站点登录状态。是否复制到当前便携版？原有数据仍会保留在原位置。",
    portableImport: "导入数据",
    portableStartFresh: "全新开始",
    portableImportFailedTitle: "未能导入现有数据",
    portableImportFailedMessage: "请完全退出所有 PolyAsk 进程，然后重新打开便携版再试。现有设置和登录状态仍保留在原位置。",
    portableLegacyInUseTitle: "请先完全退出 PolyAsk",
    portableLegacyInUseMessage: "现有数据正被另一个 PolyAsk 进程使用。请完全退出该进程，再重新打开 App\\polyask-desktop.exe。设置和登录状态仍保留在原位置。",
    portableDataConflictTitle: "未改动 PolyAsk Data",
    portableDataConflictMessage: "PolyAsk Data 中已有无法确认用途的文件。为保护这些文件，应用没有替换该目录。请先移动或备份其中的文件，再重新打开 App\\polyask-desktop.exe。",
    portableStorageFailedTitle: "便携版数据目录不可用",
    portableStorageFailedMessage: "请将 PolyAsk Portable 移到有写入权限的文件夹，然后重新打开。",
    replaceImages: "更换图片",
    removeImage: "移除{name}",
    imagesReady: "已选择 {count} 张图片",
    imageCountError: "请选择 1 至 4 张图片",
    imageTypeError: "仅支持 PNG 和 JPEG 图片",
    imageSizeError: "图片总大小不能超过 10 MiB",
    imageInvalid: "有图片无法安全读取",
    imagesBusy: "群发进行中，暂时无法添加图片",
    imageUnsupported: "{sites} 不支持图片群发，请调整站点范围",
    adjustImageScope: "调整站点范围：{count} 个不支持",
    imagePayloadInvalid: "图片载荷无效",
    attachmentUnsupported: "该站点不支持图片群发",
    attachmentFailed: "图片附件添加失败",
    attachmentTimedOut: "等待图片附件超时",
    attachmentActionRequired: "请在该站点完成图片附件操作",
    broadcastLabel: "群发提问",
    promptPlaceholder: "输入一个问题，同时发送到选中的 AI…",
    promptLabel: "提问内容",
    tierLabel: "回答档位",
    followSite: "跟随站点",
    fast: "快速",
    think: "深度思考",
    cancel: "取消",
    cancelling: "正在取消…",
    send: "发送",
    sendToOneSite: "发送至 {count} 个站点",
    sendToSites: "发送至 {count} 个站点",
    siteViews: "AI 站点视图",
    selectSite: "群发到 {site}",
    focusSite: "聚焦 {site}",
    reloadSite: "重新加载 {site}",
    loading: "加载中",
    ready: "就绪",
    sending: "发送中",
    submitted: "已发送",
    generating: "正在回答",
    answerComplete: "回答完成",
    submittedWithWarning: "已发送（有警示）",
    tierUnconfirmed: "已发送，回答档位未确认",
    composerNotFound: "未找到输入框",
    siteNotReady: "站点尚未就绪",
    submitUnconfirmed: "是否发送成功尚未确认",
    timedOut: "发送超时",
    cancelledStatus: "已取消",
    injectFailed: "未能填写提问",
    siteUnavailable: "站点视图不可用",
    answerTruncated: "该回答过长，已被截断",
    loadFailed: "页面加载失败",
    invalidResponse: "站点返回了无法识别的结果",
    siteError: "站点脚本出错",
    adapterUnavailable: "站点脚本未加载",
    operationBusy: "正在发送或新建会话，请等待完成或取消当前操作。",
    failed: "失败",
    crashed: "已停止",
    fileMenu: "文件",
    editMenu: "编辑",
    viewMenu: "视图",
    windowMenu: "窗口",
    focusPromptMenu: "聚焦提问框",
    nextSiteMenu: "聚焦下一个站点",
    previousSiteMenu: "聚焦上一个站点",
    siteBack: "在 {site} 中后退",
    siteBackMenu: "站内后退",
    siteForwardMenu: "站内前进",
    densityMenu: "界面密度",
    compactDensity: "紧凑",
    comfortableDensity: "舒适",
    siteScaleMenu: "站点缩放",
    fitSiteScale: "适应（90%）",
    actualSiteScale: "原始大小（100%）",
    commandPalette: "命令面板",
    sitesAndGroups: "站点与分组",
    siteHealth: "站点状态",
    showPageOne: "显示第 1 组站点",
    showPageTwo: "显示第 2 组站点",
    showPageThree: "显示第 3 组站点",
    chooseThinkMode: "切换为深度思考",
    chooseFastMode: "切换为快速回答",
    retryFailedCommand: "重试失败站点",
    openDriveDiagnostics: "打开 Drive 连接诊断",
    keyboardShortcuts: "快捷键速查",
    gettingStarted: "开始使用",
    guideIntro: "先用两家熟悉的站点试一个问题。本指南不会自动更改站点选择或发送问题。",
    guideChooseTitle: "选择要问的站点",
    guideChooseBody: "打开“站点与分组”，勾选你想使用的站点。建议从两家开始，需要时再增加。",
    guideLoginTitle: "在各站点登录",
    guideLoginBody: "关闭指南，直接在各站点页面登录。“站点状态”提供只读检查；无法确认状态不一定表示未登录。",
    guideAskTitle: "输入一次问题",
    guideAskBody: "输入问题，确认参与站点和回答档位，再点发送。“已发送”不代表回答已完成。提交不确定时，先查看原站，再决定是否手动重试，避免重复提问。",
    guideCompareTitle: "采集并比较回答",
    guideCompareBody: "等需要的回答准备好后，将当前回答保存为结果库快照，并选择两份对照。采集读取当前页面，请核对内容和截断提示；段落文字相同不代表事实已核实。",
    guideReturnHint: "随时从“更多”重新打开指南，或按 F1 搜索“开始使用”。关闭后回到站点，草稿会保留。",
    nextUnfinished: "转到下一个未完成站点",
    nextFailed: "转到下一个失败站点",
    checkForUpdates: "检查更新"
  },
  zhTW: {
    ...ARCHIVE_COPY.zhTW,
    ...DECISION_COPY.zhTW,
    ...TASK_FOLDER_COPY.zhTW,
    ...COMMAND_COPY.zhTW,
    ...PROMPT_LIBRARY_COPY.zhTW,
    ...PRODUCTIVITY_COPY.zhTW,
    ...SYNC_COPY.zhTW,
    ...DATA_ADMIN_COPY.zhTW,
    ...SYNTHESIS_COPY.zhTW,
    ...WORKSPACE_COPY.zhTW,
    appTitle: "PolyAsk · AI 眾答",
    startupFailedTitle: "PolyAsk 無法啟動",
    startupFailedMessage: "請重新啟動 PolyAsk。若問題仍然存在，回報時請附上診斷記錄。",
    shellLoading: "正在啟動 PolyAsk……",
    shellLoadFailed: "PolyAsk 工作區載入失敗。",
    retryShellLoad: "重試",
    displayPreferencesFailed: "無法套用顯示偏好設定",
    layoutAutoFocus: "視窗空間不足，已切為聚焦以保持可讀性；放大視窗可恢復總覽。",
    overview: "總覽",
    focus: "聚焦",
    layoutLabel: "檢視版面",
    sitePages: "網站分頁",
    sitePageLabel: "第 {page} 頁，網站 {range}",
    sitePageSending: "{count} 個傳送中",
    sitePageGenerating: "{count} 個正在回答",
    sitePageComplete: "{count} 個已完成",
    sitePageFailed: "{count} 個失敗",
    sitePageChanged: "正在顯示第 {page} 頁，共 {total} 頁",
    nextPageMenu: "下一組網站",
    previousPageMenu: "上一組網站",
    sitePageMenu: "顯示第 {page} 組網站",
    addImages: "加入圖片",
    manageImages: "管理 {count} 張圖片",
    closeImages: "關閉圖片清單",
    closeSettings: "關閉設定",
    appVersion: "PolyAsk {version} · {mode}",
    installedMode: "安裝版",
    portableMode: "可攜版",
    portableImportTitle: "是否匯入現有 PolyAsk 資料？",
    portableImportMessage: "偵測到現有 PolyAsk 的設定與網站登入狀態。是否複製到目前的可攜版？原有資料仍會保留在原位置。",
    portableImport: "匯入資料",
    portableStartFresh: "全新開始",
    portableImportFailedTitle: "無法匯入現有資料",
    portableImportFailedMessage: "請完全結束所有 PolyAsk 處理程序，再重新開啟可攜版重試。現有設定與登入狀態仍保留在原位置。",
    portableLegacyInUseTitle: "請先完全結束 PolyAsk",
    portableLegacyInUseMessage: "現有資料正由另一個 PolyAsk 處理程序使用。請完全結束該處理程序，再重新開啟 App\\polyask-desktop.exe。設定與登入狀態仍保留在原位置。",
    portableDataConflictTitle: "未變更 PolyAsk Data",
    portableDataConflictMessage: "PolyAsk Data 中已有無法確認用途的檔案。為保護這些檔案，應用程式沒有取代該資料夾。請先移動或備份其中的檔案，再重新開啟 App\\polyask-desktop.exe。",
    portableStorageFailedTitle: "可攜版資料夾無法使用",
    portableStorageFailedMessage: "請將 PolyAsk Portable 移到可寫入的資料夾，再重新開啟。",
    replaceImages: "更換圖片",
    removeImage: "移除{name}",
    imagesReady: "已選取 {count} 張圖片",
    imageCountError: "請選取 1 至 4 張圖片",
    imageTypeError: "僅支援 PNG 和 JPEG 圖片",
    imageSizeError: "圖片總大小不能超過 10 MiB",
    imageInvalid: "有圖片無法安全讀取",
    imagesBusy: "群發進行中，暫時無法加入圖片",
    imageUnsupported: "{sites} 不支援圖片群發，請調整網站範圍",
    adjustImageScope: "調整網站範圍：{count} 個不支援",
    imagePayloadInvalid: "圖片載荷無效",
    attachmentUnsupported: "該網站不支援圖片群發",
    attachmentFailed: "圖片附件加入失敗",
    attachmentTimedOut: "等待圖片附件逾時",
    attachmentActionRequired: "請在該網站完成圖片附件操作",
    broadcastLabel: "群發提問",
    promptPlaceholder: "輸入一個問題，同時傳送到選取的 AI…",
    promptLabel: "提問內容",
    tierLabel: "回答模式",
    followSite: "依網站設定",
    fast: "快速",
    think: "深度思考",
    cancel: "取消",
    cancelling: "正在取消…",
    send: "傳送",
    sendToOneSite: "傳送至 {count} 個網站",
    sendToSites: "傳送至 {count} 個網站",
    siteViews: "AI 網站檢視",
    selectSite: "傳送到 {site}",
    focusSite: "聚焦 {site}",
    reloadSite: "重新載入 {site}",
    loading: "載入中",
    ready: "就緒",
    sending: "傳送中",
    submitted: "已傳送",
    generating: "正在回答",
    answerComplete: "回答完成",
    submittedWithWarning: "已傳送（有警示）",
    tierUnconfirmed: "已傳送，回答模式未確認",
    composerNotFound: "找不到輸入框",
    siteNotReady: "網站尚未就緒",
    submitUnconfirmed: "是否送出尚未確認",
    timedOut: "傳送逾時",
    cancelledStatus: "已取消",
    injectFailed: "無法填入提問",
    siteUnavailable: "網站檢視無法使用",
    answerTruncated: "該回答過長，已被截斷",
    loadFailed: "頁面載入失敗",
    invalidResponse: "網站回傳了無法辨識的結果",
    siteError: "網站腳本發生錯誤",
    adapterUnavailable: "網站腳本未載入",
    operationBusy: "正在傳送或建立新對話，請等候完成或取消目前操作。",
    failed: "失敗",
    crashed: "已停止",
    fileMenu: "檔案",
    editMenu: "編輯",
    viewMenu: "檢視",
    windowMenu: "視窗",
    focusPromptMenu: "聚焦提問框",
    nextSiteMenu: "聚焦下一個網站",
    previousSiteMenu: "聚焦上一個網站",
    siteBack: "在 {site} 中後退",
    siteBackMenu: "網站內後退",
    siteForwardMenu: "網站內前進",
    densityMenu: "介面密度",
    compactDensity: "緊湊",
    comfortableDensity: "舒適",
    siteScaleMenu: "網站縮放",
    fitSiteScale: "適應（90%）",
    actualSiteScale: "原始大小（100%）",
    commandPalette: "指令面板",
    sitesAndGroups: "網站與群組",
    siteHealth: "網站狀態",
    showPageOne: "顯示第 1 組網站",
    showPageTwo: "顯示第 2 組網站",
    showPageThree: "顯示第 3 組網站",
    chooseThinkMode: "切換為深度思考",
    chooseFastMode: "切換為快速回答",
    retryFailedCommand: "重試失敗網站",
    openDriveDiagnostics: "開啟 Drive 連線診斷",
    keyboardShortcuts: "快速鍵一覽",
    gettingStarted: "開始使用",
    guideIntro: "先用兩家熟悉的網站試一個問題。本指南不會自動更改網站選擇或傳送問題。",
    guideChooseTitle: "選擇要問的網站",
    guideChooseBody: "開啟「網站與群組」，勾選你想使用的網站。建議從兩家開始，需要時再增加。",
    guideLoginTitle: "在各網站登入",
    guideLoginBody: "關閉指南，直接在各網站頁面登入。「網站狀態」提供唯讀檢查；無法確認狀態不一定表示未登入。",
    guideAskTitle: "輸入一次問題",
    guideAskBody: "輸入問題，確認參與網站和回答模式，再點傳送。「已傳送」不代表回答已完成。提交不確定時，先查看原網站，再決定是否手動重試，避免重複提問。",
    guideCompareTitle: "擷取並比較回答",
    guideCompareBody: "等需要的回答準備好後，將目前回答儲存為結果庫快照，並選擇兩份對照。擷取讀取目前頁面，請核對內容和截斷提示；段落文字相同不代表事實已核實。",
    guideReturnHint: "隨時從「更多」重新開啟指南，或按 F1 搜尋「開始使用」。關閉後回到網站，草稿會保留。",
    nextUnfinished: "前往下一個未完成網站",
    nextFailed: "前往下一個失敗網站",
    checkForUpdates: "檢查更新"
  }
} as const;

export type DesktopCopy = { readonly [Key in keyof typeof COPY.en]: string };
export type { DesktopLocale };
export { resolveLocale };
// 编译期保证 COPY 覆盖 DesktopLocale 的每一个值（locale.ts 是 locale 的唯一真源）。
const LOCALE_COVERAGE: Record<DesktopLocale, DesktopCopy> = COPY;
void LOCALE_COVERAGE;

export function getCopy(rawLocale: string): DesktopCopy {
  return COPY[resolveLocale(rawLocale)];
}

export function formatCopy(template: string, values: Record<string, string | number>): string {
  // 占位符允许驼峰（healthScopeSummary 的 {signIn}）；字符类漏了大写会让 token 原样裸露到界面上。
  return template.replace(/\{([A-Za-z]+)\}/g, (token, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : token
  );
}
