export const DATA_ADMIN_COPY = {
  en: {
    clearDecisionsAction: "Clear decision cards",
    clearDecisionsConfirmTitle: "Clear all decision cards?",
    clearDecisionsConfirmMessage: "All decision cards and saved excerpts will be deleted. Source results are retained. The deletions sync to your other devices.",
    localDataDecisionsCleared: "Cleared {count} decision cards",
    localDataTitle: "Local data",
    localDataDescription: "Clear this device's prompt history, saved results, or decision cards, or reset all local data.",
    localDataCloudUntouched: "Resetting never deletes data on Google Drive; reconnecting restores it.",
    clearHistoryAction: "Clear prompt history",
    clearHistoryConfirmTitle: "Clear prompt history?",
    clearHistoryConfirmMessage: "All prompt history on this device will be cleared. The deletions sync to your other devices as deletion markers.",
    clearArchivesAction: "Clear result library",
    clearArchivesConfirmTitle: "Clear result library?",
    clearArchivesConfirmMessage: "All saved results on this device will be cleared. Decision cards and their saved excerpts are retained. The deletions sync to your other devices as deletion markers.",
    resetLocalAction: "Reset all local data",
    resetLocalConfirmTitle: "Reset all local data?",
    resetLocalConfirmMessage: "Google Drive will be disconnected and everything stored on this device will be removed. Data on Google Drive is not deleted.",
    localDataConfirm: "Continue",
    localDataHistoryCleared: "Cleared {count} prompt history entries",
    localDataArchivesCleared: "Cleared {count} saved results",
    localDataReset: "Local data reset; Google Drive disconnected",
    localDataActionFailed: "Could not change local data"
  },
  zhCN: {
    clearDecisionsAction: "清空决策卡",
    clearDecisionsConfirmTitle: "清空全部决策卡？",
    clearDecisionsConfirmMessage: "全部决策卡及其摘录将被删除，来源归档仍保留。删除标记会同步到你的其它设备。",
    localDataDecisionsCleared: "已清空 {count} 张决策卡",
    localDataTitle: "本机数据",
    localDataDescription: "分别清空本机的提问历史、结果库或决策卡，或重置本机保存的全部数据。",
    localDataCloudUntouched: "重置不会删除 Google Drive 上的数据；重新连接后会恢复。",
    clearHistoryAction: "清空提问历史",
    clearHistoryConfirmTitle: "清空提问历史？",
    clearHistoryConfirmMessage: "本机全部提问历史将被清空，删除标记会同步到你的其它设备。",
    clearArchivesAction: "清空结果库",
    clearArchivesConfirmTitle: "清空结果库？",
    clearArchivesConfirmMessage: "本机保存的全部结果将被清空；决策卡及其已保存摘录仍保留。删除标记会同步到你的其它设备。",
    resetLocalAction: "重置全部本机数据",
    resetLocalConfirmTitle: "重置全部本机数据？",
    resetLocalConfirmMessage: "将断开 Google Drive 并清除本机保存的全部数据。Google Drive 上的数据不会被删除。",
    localDataConfirm: "继续",
    localDataHistoryCleared: "已清空 {count} 条提问历史",
    localDataArchivesCleared: "已清空 {count} 条结果",
    localDataReset: "本机数据已重置，Google Drive 已断开",
    localDataActionFailed: "本机数据操作失败"
  },
  zhTW: {
    clearDecisionsAction: "清空決策卡",
    clearDecisionsConfirmTitle: "清空全部決策卡？",
    clearDecisionsConfirmMessage: "全部決策卡及其摘錄將被刪除，來源封存仍保留。刪除標記會同步到你的其他裝置。",
    localDataDecisionsCleared: "已清空 {count} 張決策卡",
    localDataTitle: "本機資料",
    localDataDescription: "分別清空本機的提問歷史、結果庫或決策卡，或重設本機保存的全部資料。",
    localDataCloudUntouched: "重設不會刪除 Google Drive 上的資料；重新連線後會恢復。",
    clearHistoryAction: "清空提問歷史",
    clearHistoryConfirmTitle: "清空提問歷史？",
    clearHistoryConfirmMessage: "本機全部提問歷史將被清空，刪除標記會同步到你的其他裝置。",
    clearArchivesAction: "清空結果庫",
    clearArchivesConfirmTitle: "清空結果庫？",
    clearArchivesConfirmMessage: "本機保存的全部結果將被清空；決策卡及其已儲存摘錄仍保留。刪除標記會同步到你的其他裝置。",
    resetLocalAction: "重設全部本機資料",
    resetLocalConfirmTitle: "重設全部本機資料？",
    resetLocalConfirmMessage: "將中斷 Google Drive 連線並清除本機保存的全部資料。Google Drive 上的資料不會被刪除。",
    localDataConfirm: "繼續",
    localDataHistoryCleared: "已清空 {count} 筆提問歷史",
    localDataArchivesCleared: "已清空 {count} 筆結果",
    localDataReset: "本機資料已重設，Google Drive 已中斷連線",
    localDataActionFailed: "本機資料操作失敗"
  }
} as const;
