export const PROMPT_LIBRARY_COPY = {
  en: {
    taskTemplates: "Task templates",
    taskCompare: "Compare options",
    taskReview: "Review a draft",
    taskTechnical: "Technical review",
    taskCompareText: "Compare the following options: {{Options}}\nAudience: {{Audience}}\nBackground: {{Background}}\nConstraints: {{Constraints}}\nUse consistent criteria to compare tradeoffs, costs and risks. Separate facts from assumptions and list missing evidence. Recommend an option conditionally.",
    taskReviewText: "Review this draft: {{Draft}}\nAudience: {{Audience}}\nBackground: {{Background}}\nConstraints: {{Constraints}}\nCheck structure, clarity and factual support. Preserve the intent; identify issues before proposing edits. Do not invent facts or references.",
    taskTechnicalText: "Review this technical proposal or code: {{Material}}\nAudience: {{Audience}}\nBackground: {{Background}}\nConstraints: {{Constraints}}\nAssess correctness, security, maintainability and tradeoffs. Cite relevant portions, distinguish confirmed issues from hypotheses, and propose verification steps.",
    templateVariables: "Fill template variables",
    templateVariableHint: "Use {{Variable name}} in saved templates. Fill every field; enter “None” where not applicable.",
    templatePreview: "Question preview",
    templateApply: "Fill question",
    templateReplace: "This replaces the current draft. Sites and model tiers stay unchanged; nothing is sent.",
    templateBack: "Back to library",
    templateInvalid: "Fill every field and keep the question within 100,000 characters.",
    templateDeletePending: "Template will be deleted in 6 seconds. You can undo below.",
    undoTemplateDelete: "Undo deletion ({count})",
    templateDeleteUndone: "Template deletion undone",
    templateSaved: "Prompt template saved",
    templateDeleted: "Prompt template deleted",

    promptLibrary: "Prompt library",
    showPromptLibrary: "Prompt library",
    promptLibrarySearch: "Search templates and recent prompts",
    promptTemplates: "Templates",
    recentQuestions: "Recent prompts",
    promptTemplateName: "Template name",
    saveCurrentPrompt: "Save current prompt",
    deleteTemplate: "Delete template",
    promptLibraryEmpty: "No matching templates or recent prompts",
    promptLibrarySaveFailed: "Could not save the prompt template",
    promptLibraryDeleteFailed: "Could not delete the prompt template",
  },
  zhCN: {
    taskTemplates: "任务模板",
    taskCompare: "方案比较",
    taskReview: "文稿审阅",
    taskTechnical: "技术评审",
    taskCompareText: "请比较以下方案：{{待比较方案}}\n受众：{{受众}}\n背景：{{背景}}\n限制：{{限制}}\n用一致的标准比较收益、成本与风险，区分事实和假设，列出缺少的证据，并给出附带适用条件的建议。",
    taskReviewText: "请审阅以下文稿：{{文稿}}\n受众：{{受众}}\n背景：{{背景}}\n限制：{{限制}}\n检查结构、表达和事实依据，保留原意；先列问题，再提出具体修改。不要补造事实或参考来源。",
    taskTechnicalText: "请评审以下技术方案或代码：{{评审材料}}\n受众：{{受众}}\n背景：{{背景}}\n限制：{{限制}}\n检查正确性、安全性、可维护性及方案取舍；指出对应内容，区分确认的问题与待验证的推测，并给出验证步骤。",
    templateVariables: "填写模板变量",
    templateVariableHint: "自存模板可使用 {{变量名}}。请填齐各项；不适用时填“无”。",
    templatePreview: "问题预览",
    templateApply: "填入问题",
    templateReplace: "这会替换当前草稿，保留站点与档位，不会发送。",
    templateBack: "返回提问库",
    templateInvalid: "请填齐变量，并将问题控制在 100,000 个字符以内。",
    templateDeletePending: "模板将在 6 秒后删除，可在下方撤销。",
    undoTemplateDelete: "撤销删除（{count}）",
    templateDeleteUndone: "已撤销模板删除",
    templateSaved: "提问模板已保存",
    templateDeleted: "提问模板已删除",

    promptLibrary: "提问库",
    showPromptLibrary: "提问库",
    promptLibrarySearch: "搜索模板和最近提问",
    promptTemplates: "提问模板",
    recentQuestions: "最近提问",
    promptTemplateName: "模板名称",
    saveCurrentPrompt: "保存当前提问",
    deleteTemplate: "删除模板",
    promptLibraryEmpty: "没有匹配的模板或最近提问",
    promptLibrarySaveFailed: "无法保存提问模板",
    promptLibraryDeleteFailed: "无法删除提问模板",
  },
  zhTW: {
    taskTemplates: "任務範本",
    taskCompare: "方案比較",
    taskReview: "文稿審閱",
    taskTechnical: "技術評審",
    taskCompareText: "請比較以下方案：{{待比較方案}}\n受眾：{{受眾}}\n背景：{{背景}}\n限制：{{限制}}\n用一致的標準比較收益、成本與風險，區分事實和假設，列出缺少的證據，並給出附帶適用條件的建議。",
    taskReviewText: "請審閱以下文稿：{{文稿}}\n受眾：{{受眾}}\n背景：{{背景}}\n限制：{{限制}}\n檢查結構、表達和事實依據，保留原意；先列問題，再提出具體修改。不要捏造事實或參考來源。",
    taskTechnicalText: "請評審以下技術方案或程式碼：{{評審材料}}\n受眾：{{受眾}}\n背景：{{背景}}\n限制：{{限制}}\n檢查正確性、安全性、可維護性及方案取捨；指出對應內容，區分確認的問題與待驗證的推測，並給出驗證步驟。",
    templateVariables: "填寫範本變數",
    templateVariableHint: "自存範本可使用 {{變數名稱}}。請填齊各項；不適用時填「無」。",
    templatePreview: "問題預覽",
    templateApply: "填入問題",
    templateReplace: "這會取代目前草稿，保留網站與檔位，不會傳送。",
    templateBack: "返回提問庫",
    templateInvalid: "請填齊變數，並將問題控制在 100,000 個字元以內。",
    templateDeletePending: "範本將在 6 秒後刪除，可在下方復原。",
    undoTemplateDelete: "復原刪除（{count}）",
    templateDeleteUndone: "已復原範本刪除",
    templateSaved: "提問範本已儲存",
    templateDeleted: "提問範本已刪除",

    promptLibrary: "提問庫",
    showPromptLibrary: "提問庫",
    promptLibrarySearch: "搜尋範本和最近提問",
    promptTemplates: "提問範本",
    recentQuestions: "最近提問",
    promptTemplateName: "範本名稱",
    saveCurrentPrompt: "儲存目前提問",
    deleteTemplate: "刪除範本",
    promptLibraryEmpty: "找不到相符的範本或最近提問",
    promptLibrarySaveFailed: "無法儲存提問範本",
    promptLibraryDeleteFailed: "無法刪除提問範本",
  }
} as const;
