export const QUESTION_COPY = {
  en: {
    questionMenu: 'More actions', questionDelete: 'Delete', questionClose: 'Close history', questionRetry: 'Retry',
    questionHistory: 'Question history', questionSearch: 'Search questions…', questionEmpty: 'Your next question will appear here.',
    questionNoResults: 'No matching questions.', questionLoadFailed: 'Could not load question history. Try again.',
    questionSaveFailed: 'Could not save this question. Sending continues.', questionLoading: 'Loading history…',
    questionSaved: '{saved}/{total} sites saved', questionCopies: 'View saved answers', questionRestore: 'Open original conversations',
    questionRestoreTitle: 'Open previous conversations?', questionRestoreWarning: 'This changes the selected sites and leaves their current pages. Unsent drafts on those sites may be lost. Your top question draft stays here.',
    questionMissing: 'No saved conversation address. Read the saved answer or ask again.', questionReask: 'Use as draft',
    questionDraftTitle: 'Replace the current draft?', questionDraftWarning: 'The previous question will replace your top question draft. It will not be sent.',
    questionDeleteTitle: 'Delete this question?', questionDeleteWarning: 'Deletes this record and its saved answers on synced devices. Original AI conversations remain available on their sites.',
    questionDeleted: 'Question deleted.', questionBack: 'Back to history', questionMore: 'Load more', questionToday: 'Today', questionYesterday: 'Yesterday', questionEarlier: 'Earlier',
    questionNoAnswer: 'No answer copy was captured for this attempt.', questionAttempt: 'Attempt {number}', questionCaptured: 'Saved {time}',
    questionImages: '{count} images were sent. Images are not saved in history.', questionTruncated: 'This copy reached the text limit and is incomplete.',
    questionSnapshotNote: 'Saved copy · Original conversations may change or require you to sign in.', questionBusy: 'Opening conversations…',
    questionFailed: 'The action could not be completed. Please try again.', questionCopy: 'Copy answer', questionCopied: 'Answer copied.',
    questionStateWaiting: 'Waiting for answer', questionStatePartial: 'Partial answer', questionStateComplete: 'Complete', questionStateUnknown: 'Completion unknown', questionStateUnavailable: 'No copy available', questionStateInterrupted: 'Capture stopped',
    questionSubmissionFailed: 'Send failed', questionSubmissionUnconfirmed: 'Send unconfirmed', questionSubmissionCancelled: 'Send cancelled',
    questionOpened: 'Opened', questionAlreadyOpen: 'Already open', questionTimeout: 'Timed out', questionCancelled: 'Cancelled', questionOpenFailed: 'Could not open', questionNoUrl: 'No saved address',
    questionLegacy: 'Older text history', questionLegacyNote: 'Older entries contain question text only. Selecting one fills your draft.'
  },
  zhCN: {
    questionMenu: '更多操作', questionDelete: '删除', questionClose: '关闭历史', questionRetry: '重试',
    questionHistory: '提问历史', questionSearch: '搜索提问…', questionEmpty: '下一次提问会自动记录在这里。',
    questionNoResults: '没有找到匹配的提问。', questionLoadFailed: '提问历史读取失败，请重试。',
    questionSaveFailed: '本次提问记录未能保存，发送仍会继续。', questionLoading: '正在读取历史…',
    questionSaved: '已保存 {saved}/{total} 站回答', questionCopies: '查看副本', questionRestore: '打开原站会话',
    questionRestoreTitle: '打开之前的会话？', questionRestoreWarning: '将调整参与站点并离开它们当前的页面，站点内未发送的草稿可能丢失。顶部提问草稿会保留。',
    questionMissing: '尚无可恢复的会话地址。可以查看已保存的回答，或再次提问。', questionReask: '再次提问（填入草稿）',
    questionDraftTitle: '替换当前草稿？', questionDraftWarning: '将用这条历史提问替换顶部草稿，不会自动发送。',
    questionDeleteTitle: '删除这条提问？', questionDeleteWarning: '将删除此记录及回答副本，并同步到其他设备。AI 站点中的原会话不受影响。',
    questionDeleted: '提问记录已删除。', questionBack: '返回历史', questionMore: '加载更多', questionToday: '今天', questionYesterday: '昨天', questionEarlier: '更早',
    questionNoAnswer: '此次尝试尚未取得回答副本。', questionAttempt: '第 {number} 次尝试', questionCaptured: '保存于 {time}',
    questionImages: '当时发送了 {count} 张图片，历史中不保存图片。', questionTruncated: '已达到文本保存上限，此副本不完整。',
    questionSnapshotNote: '已保存的副本 · 原站会话可能变化，或需要重新登录。', questionBusy: '正在打开会话…',
    questionFailed: '操作未完成，请重试。', questionCopy: '复制回答', questionCopied: '回答已复制。',
    questionStateWaiting: '等待回答', questionStatePartial: '部分回答', questionStateComplete: '完整回答', questionStateUnknown: '完成状态未知', questionStateUnavailable: '未取得副本', questionStateInterrupted: '保存已停止',
    questionSubmissionFailed: '发送失败', questionSubmissionUnconfirmed: '发送未确认', questionSubmissionCancelled: '发送已取消',
    questionOpened: '已打开', questionAlreadyOpen: '已在此会话', questionTimeout: '打开超时', questionCancelled: '已取消', questionOpenFailed: '打开失败', questionNoUrl: '暂无会话地址',
    questionLegacy: '旧版文字历史', questionLegacyNote: '旧记录仅保留提问文字，点击可填入草稿。'
  },
  zhTW: {
    questionMenu: '更多操作', questionDelete: '刪除', questionClose: '關閉歷史', questionRetry: '重試',
    questionHistory: '提問歷史', questionSearch: '搜尋提問…', questionEmpty: '下一次提問會自動記錄在這裡。',
    questionNoResults: '沒有找到符合的提問。', questionLoadFailed: '提問歷史讀取失敗，請重試。',
    questionSaveFailed: '本次提問記錄未能儲存，傳送仍會繼續。', questionLoading: '正在讀取歷史…',
    questionSaved: '已儲存 {saved}/{total} 站回答', questionCopies: '查看副本', questionRestore: '開啟原站對話',
    questionRestoreTitle: '開啟之前的對話？', questionRestoreWarning: '將調整參與站點並離開它們目前的頁面，站點內未傳送的草稿可能遺失。頂部提問草稿會保留。',
    questionMissing: '尚無可還原的對話網址。可以查看已儲存的回答，或再次提問。', questionReask: '再次提問（填入草稿）',
    questionDraftTitle: '取代目前草稿？', questionDraftWarning: '將用這條歷史提問取代頂部草稿，不會自動傳送。',
    questionDeleteTitle: '刪除這條提問？', questionDeleteWarning: '將刪除此記錄及回答副本，並同步到其他裝置。AI 站點中的原對話不受影響。',
    questionDeleted: '提問記錄已刪除。', questionBack: '返回歷史', questionMore: '載入更多', questionToday: '今天', questionYesterday: '昨天', questionEarlier: '更早',
    questionNoAnswer: '此次嘗試尚未取得回答副本。', questionAttempt: '第 {number} 次嘗試', questionCaptured: '儲存於 {time}',
    questionImages: '當時傳送了 {count} 張圖片，歷史中不儲存圖片。', questionTruncated: '已達文字儲存上限，此副本不完整。',
    questionSnapshotNote: '已儲存的副本 · 原站對話可能變更，或需要重新登入。', questionBusy: '正在開啟對話…',
    questionFailed: '操作未完成，請重試。', questionCopy: '複製回答', questionCopied: '回答已複製。',
    questionStateWaiting: '等待回答', questionStatePartial: '部分回答', questionStateComplete: '完整回答', questionStateUnknown: '完成狀態未知', questionStateUnavailable: '未取得副本', questionStateInterrupted: '儲存已停止',
    questionSubmissionFailed: '傳送失敗', questionSubmissionUnconfirmed: '傳送未確認', questionSubmissionCancelled: '傳送已取消',
    questionOpened: '已開啟', questionAlreadyOpen: '已在此對話', questionTimeout: '開啟逾時', questionCancelled: '已取消', questionOpenFailed: '開啟失敗', questionNoUrl: '暫無對話網址',
    questionLegacy: '舊版文字歷史', questionLegacyNote: '舊記錄僅保留提問文字，點選可填入草稿。'
  }
} as const;
