export const SETTINGS_RECOVERY_COPY = {
  en: {
    settingsDisplayTitle: 'Display and reading',
    settingsDensityLabel: 'App density',
    settingsScaleLabel: 'Default site page scale',
    settingsDisplayFailed: 'Could not apply the display preferences. The accepted preferences are still shown; try again.',
    settingsDensityScope: 'Density changes the app controls and spacing, independently of the site pages.',
    settingsScaleScope: 'The default scale applies to sites you have not zoomed manually. The focused main site defaults to 100%. Manual site zoom takes priority; Ctrl+0 restores that site to 100%.',
    settingsDisplayUpdating: 'Applying display preferences…',
    settingsAdvancedData: 'Advanced data management',
    settingsAdvancedHint: 'Category deletions sync to other devices. Resetting removes local data and disconnects Google Drive without deleting cloud data.',
    localDataStatsLoading: 'Reading current counts…',
    localDataStatsFailed: 'Could not read the counts. Read them again before continuing.',
    localDataStatsRetry: 'Read counts again',
    localDataStatsChanged: 'Counts changed. Review them and confirm again.',
    localDataStatsSnapshot: 'These are active records before confirmation. Execution clears all current records in this category; counts can change. The completion result shows the actual count.',
    localDataResetSnapshot: 'These are active business records before confirmation. Resetting also removes local settings and sync metadata. Counts can change before execution.',
    localDataBackupFirst: 'Back up business data first',
    localDataHistoryCount: 'Prompt history: {count}',
    localDataArchivesCount: 'Saved results: {count}',
    localDataDecisionsCount: 'Decision cards: {count}',
    localDataFoldersCount: 'Folders: {count}',
    localDataAnswersCount: 'Answer copies: {count}',
    localDataMembershipsCount: 'Folder associations: {count}',
    localDataTemplatesCount: 'Saved templates: {count}',
    localDataGroupsCount: 'Site groups: {count}',
    localDataWorkspaceCount: 'Workspace settings: {count}',
    localDataNoActiveRecords: 'There are no active records in this category.',
    healthRecoveryTitle: 'Recommended first step',
    healthRecoveryMore: 'More recovery actions',
    healthRecoveryCacheScope: 'Cache clearing removes only Service Worker and CacheStorage data. Cookies, localStorage and IndexedDB are kept. It does not fix changed site controls.',
    healthAdviceBusy: 'This site is working. Focus it to view the current task; reloading is unavailable.',
    healthAdviceUnconfirmed: 'Submission or completion is unconfirmed. Check the current conversation before deciding what to do next.',
    healthAdviceSignIn: 'Focus the site to finish signing in, then check its status again.',
    healthAdvicePage: 'The page failed to load or stopped. Try a normal reload first.',
    healthAdviceReach: 'The input area could not be found. Check that the site has loaded and whether it asks you to sign in.',
    healthAdviceControl: 'Check the site controls first. If the issue continues, copy the diagnostic report; clearing cache does not fix changed site controls.',
    healthAdviceProbe: 'A reliable check was not available. Check again; if the issue continues, copy the diagnostic report.',
    healthAdviceTier: 'Check the model and mode on the site. An unrecognized mode alone does not mean the site cannot receive prompts.',
    healthAdviceCapture: 'Check that the answer is visible. This warning concerns saved answer copies; broadcasting remains available.',
    healthAdviceUnknown: 'The site status is unknown. Run a read-only check first.',
    healthAdviceReady: 'The site is ready. Focus it to view its current conversation.'
  },
  zhCN: {
    settingsDisplayTitle: '显示与阅读',
    settingsDensityLabel: '外壳密度',
    settingsScaleLabel: '站点网页默认比例',
    settingsDisplayFailed: '未能应用显示偏好，仍显示已生效的设置，请重试。',
    settingsDensityScope: '密度调整应用外壳的控件和间距，与站点网页缩放相互独立。',
    settingsScaleScope: '默认比例用于尚未手动缩放的站点，聚焦主站默认 100%。本站手动缩放优先；Ctrl+0 将本站恢复为 100%。',
    settingsDisplayUpdating: '正在应用显示偏好…',
    settingsAdvancedData: '高级数据管理',
    settingsAdvancedHint: '分类删除会同步到其他设备；重置会断开 Google Drive 并清除本机数据，不删除云端数据。',
    localDataStatsLoading: '正在读取当前数量…',
    localDataStatsFailed: '无法读取数量，请重新读取后再继续。',
    localDataStatsRetry: '重新读取数量',
    localDataStatsChanged: '数据数量已变化，请核对后再次确认。',
    localDataStatsSnapshot: '以下为确认前的活动记录。执行时将清空该类别的全部当前记录，数量可能变化，以完成结果为准。',
    localDataResetSnapshot: '以下为确认前的活动业务记录。重置还会清除本机设置和同步元数据，执行前数量可能变化。',
    localDataBackupFirst: '先备份业务数据',
    localDataHistoryCount: '提问历史：{count} 条',
    localDataArchivesCount: '保存的结果：{count} 条',
    localDataDecisionsCount: '决策卡：{count} 张',
    localDataFoldersCount: '文件夹：{count} 个',
    localDataAnswersCount: '回答副本：{count} 份',
    localDataMembershipsCount: '文件夹关联：{count} 条',
    localDataTemplatesCount: '已保存模板：{count} 个',
    localDataGroupsCount: '站点分组：{count} 个',
    localDataWorkspaceCount: '工作区设置：{count} 份',
    localDataNoActiveRecords: '该类别没有活动记录。',
    healthRecoveryTitle: '建议先做这一步',
    healthRecoveryMore: '更多恢复操作',
    healthRecoveryCacheScope: '清缓存仅清除 Service Worker 和 CacheStorage，保留 Cookie、localStorage 和 IndexedDB；不能修复站点控件改版。',
    healthAdviceBusy: '本站正在工作。可聚焦查看当前任务，暂时不能重新加载。',
    healthAdviceUnconfirmed: '发送或完成状态尚未确认。请先查看当前对话，再决定下一步。',
    healthAdviceSignIn: '先聚焦站点完成登录，再检查站点状态。',
    healthAdvicePage: '页面加载失败或已停止，建议先尝试普通重新加载。',
    healthAdviceReach: '暂未找到输入区域，请先检查页面是否载入，以及是否要求登录。',
    healthAdviceControl: '先查看站点控件；持续异常时复制诊断报告。清缓存不能修复站点控件改版。',
    healthAdviceProbe: '尚未取得可靠检查结果。请再次检查，持续异常时复制诊断报告。',
    healthAdviceTier: '请核对站点上的模型和档位。仅档位无法识别，不代表本站无法接收提问。',
    healthAdviceCapture: '请查看回答是否可见。此提示影响回答副本采集，仍可群发提问。',
    healthAdviceUnknown: '尚未确认本站状态，建议先运行只读检查。',
    healthAdviceReady: '本站可提问，可聚焦查看当前对话。'
  },
  zhTW: {
    settingsDisplayTitle: '顯示與閱讀',
    settingsDensityLabel: '外殼密度',
    settingsScaleLabel: '網站頁面預設比例',
    settingsDisplayFailed: '無法套用顯示偏好，仍顯示已套用的設定，請重試。',
    settingsDensityScope: '密度調整應用程式外殼的控制項與間距，與網站頁面縮放相互獨立。',
    settingsScaleScope: '預設比例用於尚未手動縮放的網站，聚焦主站預設為 100%。本站手動縮放優先；Ctrl+0 將本站還原為 100%。',
    settingsDisplayUpdating: '正在套用顯示偏好…',
    settingsAdvancedData: '進階資料管理',
    settingsAdvancedHint: '分類刪除會同步至其他裝置；重設會中斷 Google Drive 並清除本機資料，不刪除雲端資料。',
    localDataStatsLoading: '正在讀取目前數量…',
    localDataStatsFailed: '無法讀取數量，請重新讀取後再繼續。',
    localDataStatsRetry: '重新讀取數量',
    localDataStatsChanged: '資料數量已變動，請核對後再次確認。',
    localDataStatsSnapshot: '以下是確認前的有效紀錄。執行時會清空此分類的所有目前紀錄，數量可能變動，以完成結果為準。',
    localDataResetSnapshot: '以下是確認前的有效業務紀錄。重設也會清除本機設定與同步中繼資料，執行前數量可能變動。',
    localDataBackupFirst: '先備份業務資料',
    localDataHistoryCount: '提問歷史：{count} 筆',
    localDataArchivesCount: '儲存的結果：{count} 筆',
    localDataDecisionsCount: '決策卡：{count} 張',
    localDataFoldersCount: '資料夾：{count} 個',
    localDataAnswersCount: '回答副本：{count} 份',
    localDataMembershipsCount: '資料夾關聯：{count} 筆',
    localDataTemplatesCount: '已儲存範本：{count} 個',
    localDataGroupsCount: '網站群組：{count} 個',
    localDataWorkspaceCount: '工作區設定：{count} 份',
    localDataNoActiveRecords: '此分類沒有有效紀錄。',
    healthRecoveryTitle: '建議先做這一步',
    healthRecoveryMore: '更多復原操作',
    healthRecoveryCacheScope: '清快取僅清除 Service Worker 與 CacheStorage，保留 Cookie、localStorage 和 IndexedDB；無法修復網站控制項改版。',
    healthAdviceBusy: '本站正在工作。可聚焦查看目前任務，暫時無法重新載入。',
    healthAdviceUnconfirmed: '傳送或完成狀態尚未確認。請先查看目前對話，再決定下一步。',
    healthAdviceSignIn: '先聚焦網站完成登入，再檢查網站狀態。',
    healthAdvicePage: '頁面載入失敗或已停止，建議先嘗試一般重新載入。',
    healthAdviceReach: '尚未找到輸入區域，請先檢查頁面是否載入，以及是否要求登入。',
    healthAdviceControl: '先檢查網站控制項；持續異常時複製診斷報告。清快取無法修復網站控制項改版。',
    healthAdviceProbe: '尚未取得可靠檢查結果。請再次檢查，持續異常時複製診斷報告。',
    healthAdviceTier: '請核對網站上的模型與模式。僅模式無法辨識，不代表本站無法接收提問。',
    healthAdviceCapture: '請查看回答是否可見。此提示影響回答副本擷取，仍可群發提問。',
    healthAdviceUnknown: '尚未確認本站狀態，建議先執行唯讀檢查。',
    healthAdviceReady: '本站可提問，可聚焦查看目前對話。'
  }
} as const;
