export const SITE_PARTICIPATION_COPY = {
  en: {
    participationLabel: 'Send to',
    participationSummary: 'Sending to {participating} sites',
    participationSessionHint: 'Uncheck a site to skip future broadcasts in this app session. Its page stays open; close it to release resources.',
    participationResourcesHint: 'Pages kept open still use resources. Close a page to release it.',
    sitePageRetained: 'Page open, skipped',
    sitePageClosed: 'Page closed',
    closeSitePage: 'Close {site} page',
    sitePageCloseTitle: 'Close {site}?',
    sitePageCloseMessage: 'This releases the current page. Unsent drafts and the scroll position may be lost. Login information and saved answer copies remain. Reopening loads the site entrance.',
    sitePageCloseConfirm: 'Close page',
    sitePageCloseSending: 'This page is submitting a question. Wait for the operation to settle before closing it.',
    sitePageCloseGeneration: 'Generation has not been confirmed finished. Keep this page open.',
    sitePageCloseCapture: 'An answer copy is still being saved. Keep this page open.',
    sitePageCloseNavigation: 'This page is navigating. Wait before closing it.',
    sitePageCloseBusy: 'Another operation is still active. Try closing the page after it settles.',
    sitePageCloseChanged: 'The page changed after the preview. Check it again before closing.',
    sitePageNotOpen: 'This page is already closed.',
    sitePageCloseFailed: 'The close result could not be confirmed. Check your open pages.',
    sitePagesOpening: 'Opening the requested pages…',
    siteParticipationFailed: 'The requested pages could not be opened. They were not added to the broadcast.',
    sitePagePreviewPending: 'Checking whether this page can be closed…',
    adjustSiteOrder: 'Adjust page order', finishSiteOrder: 'Finish adjusting',
    siteOrderSaveHint: 'Each move is saved immediately. Finishing only exits adjustment.'
  },
  zhCN: {
    participationLabel: '发送站点',
    participationSummary: '发送到 {participating} 站',
    participationSessionHint: '取消勾选后，本次使用期间不再发送到该站；页面仍保留，关闭可释放资源。',
    participationResourcesHint: '保留打开的页面仍占资源；关闭页面可以释放。',
    sitePageRetained: '保留页面，不发送',
    sitePageClosed: '页面已关闭',
    closeSitePage: '关闭 {site} 页面',
    sitePageCloseTitle: '关闭 {site}？',
    sitePageCloseMessage: '这会释放当前页面，未发送草稿和滚动位置可能丢失。登录信息与已保存回答副本保留；重新打开会加载本站入口。',
    sitePageCloseConfirm: '关闭页面',
    sitePageCloseSending: '本站正在提交问题，请等操作结算后再关闭。',
    sitePageCloseGeneration: '尚未确认本站生成结束，请保留页面。',
    sitePageCloseCapture: '本站回答副本仍在保存，请保留页面。',
    sitePageCloseNavigation: '本站正在导航，请稍后再关闭。',
    sitePageCloseBusy: '另一项操作尚未结算，请等结束后再关闭页面。',
    sitePageCloseChanged: '页面在核对后发生变化，请重新查看再关闭。',
    sitePageNotOpen: '此页面已经关闭。',
    sitePageCloseFailed: '尚未确认关闭结果，请查看当前打开的页面。',
    sitePagesOpening: '正在打开所需页面…',
    siteParticipationFailed: '无法打开所需页面，它们未加入群发范围。',
    sitePagePreviewPending: '正在检查此页面能否关闭…',
    adjustSiteOrder: '调整页面顺序', finishSiteOrder: '完成调整',
    siteOrderSaveHint: '每次移动立即保存；完成只退出调整。'
  },
  zhTW: {
    participationLabel: '傳送網站',
    participationSummary: '傳送至 {participating} 站',
    participationSessionHint: '取消勾選後，本次使用期間不再傳送至該站；頁面仍保留，關閉可釋放資源。',
    participationResourcesHint: '保留開啟的頁面仍占資源；關閉頁面可以釋放。',
    sitePageRetained: '保留頁面，不傳送',
    sitePageClosed: '頁面已關閉',
    closeSitePage: '關閉 {site} 頁面',
    sitePageCloseTitle: '關閉 {site}？',
    sitePageCloseMessage: '這會釋放目前頁面，未傳送草稿和捲動位置可能遺失。登入資訊與已儲存回答副本保留；重新開啟會載入本站入口。',
    sitePageCloseConfirm: '關閉頁面',
    sitePageCloseSending: '本站正在提交問題，請等操作結算後再關閉。',
    sitePageCloseGeneration: '尚未確認本站生成結束，請保留頁面。',
    sitePageCloseCapture: '本站回答副本仍在儲存，請保留頁面。',
    sitePageCloseNavigation: '本站正在導覽，請稍後再關閉。',
    sitePageCloseBusy: '另一項操作尚未結算，請等結束後再關閉頁面。',
    sitePageCloseChanged: '頁面在核對後發生變化，請重新查看再關閉。',
    sitePageNotOpen: '此頁面已經關閉。',
    sitePageCloseFailed: '尚未確認關閉結果，請查看目前開啟的頁面。',
    sitePagesOpening: '正在開啟所需頁面…',
    siteParticipationFailed: '無法開啟所需頁面，它們未加入群發範圍。',
    sitePagePreviewPending: '正在檢查此頁面能否關閉…',
    adjustSiteOrder: '調整頁面順序', finishSiteOrder: '完成調整',
    siteOrderSaveHint: '每次移動立即儲存；完成只退出調整。'
  }
} as const;

export type SiteParticipationCopy = { readonly [K in keyof typeof SITE_PARTICIPATION_COPY.en]: string };
