export const SYNC_COPY = {
  en: {
    settings: "Settings",
    syncTitle: "Google Drive sync",
    syncDescription: "Sync site scope, groups, prompt history, templates, saved results and decision cards through PolyAsk's private Drive app folder. After syncing decision cards, older devices need an update to resume sync.",
    syncConnected: "Connected",
    syncDisconnected: "Not connected",
    syncPending: "{count} pending",
    syncLastSuccess: "Last synced {time}",
    syncNever: "Not synced yet",
    syncConnect: "Connect Google Drive",
    syncNow: "Sync now",
    syncDisconnect: "Disconnect",
    syncRevoke: "Revoke Google access",
    syncRevokeHint: "This device still holds a Google sign-in. Revoke it to remove the stored token.",
    syncClearTitle: "Delete cloud data",
    syncClearDescription: "Permanently delete only PolyAsk files from the private Drive app folder. Local data stays on this device.",
    syncClearInstruction: "Type DELETE to enable",
    syncClear: "Delete cloud data",
    syncOauthMissing: "This build is missing its Google Desktop OAuth credentials. Before packaging, add both clientId and clientSecret to resources/oauth.json, or set POLYASK_GOOGLE_DESKTOP_CLIENT_ID and POLYASK_GOOGLE_DESKTOP_CLIENT_SECRET.",
    syncStorageWarning: "Your Linux keyring is unavailable. The refresh token will remain in memory for this session and will not be written to disk.",
    syncReadOnly: "A newer device wrote an unsupported sync format. Downloads remain available; uploads are paused to protect cloud data.",
    syncStateIdle: "Up to date",
    syncStateLocalOnly: "Local only",
    syncStateAuthorizing: "Waiting for browser authorization…",
    syncStateConnecting: "Checking Google Drive access…",
    syncStateSyncing: "Syncing…",
    syncStateOffline: "Offline; local changes are queued",
    syncStateAuth: "Sign in again to continue",
    syncStateBlocked: "Google Drive access is blocked",
    syncStateWaiting: "Google is busy; retry scheduled",
    syncStateSchema: "Read-only compatibility mode",
    syncStateError: "Sync failed",
    syncReasonDriveDisabled: "Enable Google Drive API for this OAuth project",
    syncReasonQuota: "Google Drive quota or rate limit reached",
    syncReasonPolicy: "Google policy denied Drive access",
    syncReasonOauthMissing: "OAuth is not configured",
    syncReasonOauthCallbackTimeout: "PolyAsk did not receive browser authorization in time. Try connecting again.",
    syncReasonOauthNetworkTimeout: "Browser authorization completed, but Google sign-in timed out. Check your network, then try again.",
    syncReasonOauthNetwork: "Browser authorization completed, but PolyAsk could not reach Google sign-in services. Check your network, then try again.",
    syncReasonOauthInvalidGrant: "Google rejected the authorization code (invalid_grant). Reconnect once; if it still fails, report this error code.",
    syncReasonOauthInvalidClient: "This build's Google OAuth client configuration is invalid (invalid_client). The app configuration needs to be updated.",
    syncReasonOauthRedirectMismatch: "Google rejected the local callback address (redirect_uri_mismatch). The app configuration needs to be updated.",
    syncReasonOauthRefreshMissing: "Google issued an access token but did not return the refresh token required to stay connected. Revoke PolyAsk's access in your Google Account, then reconnect.",
    syncReasonOauthProvider: "Google rejected the token request (error code: {code}). Include this code when reporting the issue so the OAuth configuration can be diagnosed.",
    syncReasonOauthRejected: "Google did not accept this authorization. Try connecting again.",
    syncReasonOauthResponse: "Google sign-in returned a response PolyAsk could not read. Try connecting again.",
    syncReasonTokenStorage: "Authorization completed, but PolyAsk could not securely save your sign-in. Make sure PolyAsk can write to its data folder, then try again.",
    syncReasonDriveNetworkTimeout: "Authorization completed, but connecting to Google Drive timed out. Check your network, then try again.",
    syncReasonDriveNetwork: "Authorization completed, but PolyAsk could not reach Google Drive. Check your network, then try again.",
    syncReasonDriveResponse: "Google Drive returned a response PolyAsk could not read. Try again later.",
    syncReasonDriveUnauthorized: "Authorization completed, but Google Drive rejected the access token (HTTP 401). Revoke PolyAsk's access in your Google Account, then reconnect.",
    syncReasonTimeout: "Connection timed out. Check your network or proxy, then try again.",
    syncReasonClearPending: "A cloud deletion is still finishing. Sync resumes once it ends.",
    syncReasonRevokeFailed: "PolyAsk disconnected locally, but Google did not confirm the revocation. Remove PolyAsk from your Google Account permissions to be sure.",
    syncPrivacy: "Cloud records are plain JSON and are not end-to-end encrypted. PolyAsk requests only drive.appdata access.",
    syncActionFailed: "Sync action failed",
    syncDiagnosticsTitle: "Connection diagnostics",
    syncDiagnosticsDescription: "Review each step from app configuration through the latest Drive sync.",
    syncDiagnosticsShow: "Show connection diagnostics",
    syncDiagnosticsHide: "Hide connection diagnostics",
    syncDiagnosticsCopy: "Copy diagnostic report",
    syncDiagnosticsCopied: "Diagnostic report copied",
    syncDiagnosticsCopyFailed: "Could not copy the diagnostic report",
    syncDiagnosticsRefreshFailed: "Could not refresh connection diagnostics",
    syncDiagnosticsPrivacy: "The report includes only app and connection state. It excludes tokens, account details, prompts, file names, and local paths.",
    syncStageOauthConfig: "OAuth configuration",
    syncStageBrowserAuth: "Browser authorization",
    syncStageTokenExchange: "Authorization code exchange",
    syncStageTokenStorage: "Token storage",
    syncStageDriveAccess: "Drive access",
    syncStageLastSync: "Latest sync",
    syncDiagnosticOk: "Passed",
    syncDiagnosticChecking: "Checking",
    syncDiagnosticWarning: "Needs attention",
    syncDiagnosticFailed: "Failed",
    syncDiagnosticUnknown: "Not checked"
  },
  zhCN: {
    settings: "设置",
    syncTitle: "Google Drive 同步",
    syncDescription: "通过 PolyAsk 的 Drive 应用专属目录同步站点范围、分组、提问历史、模板、结果库和决策卡。同步决策卡后，旧版设备需升级才能恢复同步。",
    syncConnected: "已连接",
    syncDisconnected: "未连接",
    syncPending: "{count} 项待同步",
    syncLastSuccess: "上次同步 {time}",
    syncNever: "尚未同步",
    syncConnect: "连接 Google Drive",
    syncNow: "立即同步",
    syncDisconnect: "断开连接",
    syncRevoke: "撤销 Google 授权",
    syncRevokeHint: "本机仍保存着 Google 登录凭据。撤销授权可清除已保存的令牌。",
    syncClearTitle: "删除云端数据",
    syncClearDescription: "永久删除 Drive 应用专属目录内的 PolyAsk 文件；本机数据会保留。",
    syncClearInstruction: "输入 DELETE 后启用",
    syncClear: "删除云端数据",
    syncOauthMissing: "当前构建缺少 Google 桌面 OAuth 凭据。打包前，请在 resources/oauth.json 中同时配置 clientId 和 clientSecret，或设置 POLYASK_GOOGLE_DESKTOP_CLIENT_ID 与 POLYASK_GOOGLE_DESKTOP_CLIENT_SECRET。",
    syncStorageWarning: "Linux 密钥环不可用。刷新令牌仅在本次会话保留于内存，不会写入磁盘。",
    syncReadOnly: "其他设备写入了当前版本不支持的同步格式。仍可下载，已暂停上传以保护云端数据。",
    syncStateIdle: "已是最新",
    syncStateLocalOnly: "仅保存在本机",
    syncStateAuthorizing: "正在等待浏览器完成授权……",
    syncStateConnecting: "正在检查 Google Drive 访问权限……",
    syncStateSyncing: "正在同步…",
    syncStateOffline: "当前离线，本机变更已排队",
    syncStateAuth: "请重新登录后继续",
    syncStateBlocked: "Google Drive 访问受阻",
    syncStateWaiting: "Google 服务繁忙，已安排重试",
    syncStateSchema: "只读兼容模式",
    syncStateError: "同步失败",
    syncReasonDriveDisabled: "请为此 OAuth 项目启用 Google Drive API",
    syncReasonQuota: "已达到 Google Drive 配额或请求限制",
    syncReasonPolicy: "Google 策略拒绝了 Drive 访问",
    syncReasonOauthMissing: "尚未配置 OAuth",
    syncReasonOauthCallbackTimeout: "PolyAsk 未能及时收到浏览器授权结果，请重新连接。",
    syncReasonOauthNetworkTimeout: "浏览器授权已完成，但连接 Google 登录服务超时。请检查网络后重试。",
    syncReasonOauthNetwork: "浏览器授权已完成，但 PolyAsk 无法连接 Google 登录服务。请检查网络后重试。",
    syncReasonOauthInvalidGrant: "Google 拒绝了本次授权码（invalid_grant）。请重新连接一次；若仍失败，请反馈此错误代码。",
    syncReasonOauthInvalidClient: "当前版本的 Google OAuth 客户端配置无效（invalid_client），需要更新应用配置。",
    syncReasonOauthRedirectMismatch: "Google 拒绝了本机回调地址（redirect_uri_mismatch），需要更新应用配置。",
    syncReasonOauthRefreshMissing: "Google 已签发访问令牌，但未返回持续连接所需的刷新令牌。请先在 Google 账号中撤销 PolyAsk 的访问权限，再重新连接。",
    syncReasonOauthProvider: "Google 拒绝了令牌请求（错误代码：{code}）。反馈问题时请附上此代码，以便定位 OAuth 配置问题。",
    syncReasonOauthRejected: "Google 未接受本次授权，请重新连接。",
    syncReasonOauthResponse: "Google 登录服务返回了 PolyAsk 无法识别的响应，请重新连接。",
    syncReasonTokenStorage: "授权已完成，但 PolyAsk 无法安全保存登录信息。请确认 PolyAsk 可以写入数据目录后重试。",
    syncReasonDriveNetworkTimeout: "授权已完成，但连接 Google Drive 超时。请检查网络后重试。",
    syncReasonDriveNetwork: "授权已完成，但 PolyAsk 无法连接 Google Drive。请检查网络后重试。",
    syncReasonDriveResponse: "Google Drive 返回了 PolyAsk 无法识别的响应，请稍后重试。",
    syncReasonDriveUnauthorized: "授权已完成，但 Google Drive 拒绝了访问令牌（HTTP 401）。请先撤销 PolyAsk 的访问权限，再重新连接。",
    syncReasonTimeout: "连接超时。请检查网络或代理设置后重试。",
    syncReasonClearPending: "云端删除尚未结束，完成后会自动恢复同步。",
    syncReasonRevokeFailed: "已在本机断开连接，但 Google 未确认撤销。请到 Google 账号的第三方权限中移除 PolyAsk 以确保撤销生效。",
    syncPrivacy: "云端记录为明文 JSON，不提供端到端加密；PolyAsk 仅申请 drive.appdata 权限。",
    syncActionFailed: "同步操作失败",
    syncDiagnosticsTitle: "连接诊断",
    syncDiagnosticsDescription: "逐项检查从应用配置到最近一次 Drive 同步的各个环节。",
    syncDiagnosticsShow: "展开连接诊断",
    syncDiagnosticsHide: "收起连接诊断",
    syncDiagnosticsCopy: "复制诊断报告",
    syncDiagnosticsCopied: "已复制诊断报告",
    syncDiagnosticsCopyFailed: "无法复制诊断报告",
    syncDiagnosticsRefreshFailed: "无法刷新连接诊断",
    syncDiagnosticsPrivacy: "报告仅包含应用与连接状态，不包含令牌、账号信息、提问内容、文件名或本机路径。",
    syncStageOauthConfig: "OAuth 配置",
    syncStageBrowserAuth: "系统浏览器授权",
    syncStageTokenExchange: "授权码交换",
    syncStageTokenStorage: "令牌存储",
    syncStageDriveAccess: "Drive 访问权限",
    syncStageLastSync: "最近一次同步",
    syncDiagnosticOk: "通过",
    syncDiagnosticChecking: "正在检查",
    syncDiagnosticWarning: "需要注意",
    syncDiagnosticFailed: "失败",
    syncDiagnosticUnknown: "尚未检查"
  },
  zhTW: {
    settings: "設定",
    syncTitle: "Google Drive 同步",
    syncDescription: "透過 PolyAsk 的 Drive 應用程式專屬資料夾同步網站範圍、群組、提問記錄、範本、結果庫與決策卡。同步決策卡後，舊版裝置須升級才能恢復同步。",
    syncConnected: "已連線",
    syncDisconnected: "未連線",
    syncPending: "{count} 項待同步",
    syncLastSuccess: "上次同步 {time}",
    syncNever: "尚未同步",
    syncConnect: "連線 Google Drive",
    syncNow: "立即同步",
    syncDisconnect: "中斷連線",
    syncRevoke: "撤銷 Google 授權",
    syncRevokeHint: "本機仍保存著 Google 登入憑證。撤銷授權可清除已儲存的權杖。",
    syncClearTitle: "刪除雲端資料",
    syncClearDescription: "永久刪除 Drive 應用程式專屬資料夾內的 PolyAsk 檔案；本機資料會保留。",
    syncClearInstruction: "輸入 DELETE 後啟用",
    syncClear: "刪除雲端資料",
    syncOauthMissing: "目前組建缺少 Google 桌面 OAuth 憑證。封裝前，請在 resources/oauth.json 中同時設定 clientId 和 clientSecret，或設定 POLYASK_GOOGLE_DESKTOP_CLIENT_ID 與 POLYASK_GOOGLE_DESKTOP_CLIENT_SECRET。",
    syncStorageWarning: "Linux 金鑰圈無法使用。重新整理權杖僅在本次工作階段保留於記憶體，不會寫入磁碟。",
    syncReadOnly: "其他裝置寫入了目前版本不支援的同步格式。仍可下載，已暫停上傳以保護雲端資料。",
    syncStateIdle: "已是最新",
    syncStateLocalOnly: "僅儲存在本機",
    syncStateAuthorizing: "正在等待瀏覽器完成授權……",
    syncStateConnecting: "正在檢查 Google Drive 存取權限……",
    syncStateSyncing: "正在同步…",
    syncStateOffline: "目前離線，本機變更已排入佇列",
    syncStateAuth: "請重新登入後繼續",
    syncStateBlocked: "Google Drive 存取受阻",
    syncStateWaiting: "Google 服務忙碌，已安排重試",
    syncStateSchema: "唯讀相容模式",
    syncStateError: "同步失敗",
    syncReasonDriveDisabled: "請為此 OAuth 專案啟用 Google Drive API",
    syncReasonQuota: "已達 Google Drive 配額或要求限制",
    syncReasonPolicy: "Google 政策拒絕了 Drive 存取",
    syncReasonOauthMissing: "尚未設定 OAuth",
    syncReasonOauthCallbackTimeout: "PolyAsk 未能及時收到瀏覽器授權結果，請重新連線。",
    syncReasonOauthNetworkTimeout: "瀏覽器授權已完成，但連線至 Google 登入服務逾時。請檢查網路後再試一次。",
    syncReasonOauthNetwork: "瀏覽器授權已完成，但 PolyAsk 無法連線至 Google 登入服務。請檢查網路後再試一次。",
    syncReasonOauthInvalidGrant: "Google 拒絕了這次授權碼（invalid_grant）。請重新連線一次；若仍失敗，請回報此錯誤代碼。",
    syncReasonOauthInvalidClient: "目前版本的 Google OAuth 用戶端設定無效（invalid_client），需要更新應用程式設定。",
    syncReasonOauthRedirectMismatch: "Google 拒絕了本機回呼位址（redirect_uri_mismatch），需要更新應用程式設定。",
    syncReasonOauthRefreshMissing: "Google 已核發存取權杖，但未返回維持連線所需的重新整理權杖。請先在 Google 帳戶中撤銷 PolyAsk 的存取權，再重新連線。",
    syncReasonOauthProvider: "Google 拒絕了權杖要求（錯誤代碼：{code}）。回報問題時請附上此代碼，以便找出 OAuth 設定問題。",
    syncReasonOauthRejected: "Google 未接受這次授權，請重新連線。",
    syncReasonOauthResponse: "Google 登入服務返回了 PolyAsk 無法辨識的回應，請重新連線。",
    syncReasonTokenStorage: "授權已完成，但 PolyAsk 無法安全儲存登入資訊。請確認 PolyAsk 可以寫入資料夾後再試一次。",
    syncReasonDriveNetworkTimeout: "授權已完成，但連線至 Google Drive 逾時。請檢查網路後再試一次。",
    syncReasonDriveNetwork: "授權已完成，但 PolyAsk 無法連線至 Google Drive。請檢查網路後再試一次。",
    syncReasonDriveResponse: "Google Drive 返回了 PolyAsk 無法辨識的回應，請稍後再試一次。",
    syncReasonDriveUnauthorized: "授權已完成，但 Google Drive 拒絕了存取權杖（HTTP 401）。請先撤銷 PolyAsk 的存取權，再重新連線。",
    syncReasonTimeout: "連線逾時。請檢查網路或代理設定後再試一次。",
    syncReasonClearPending: "雲端刪除尚未結束，完成後會自動恢復同步。",
    syncReasonRevokeFailed: "已在本機中斷連線，但 Google 未確認撤銷。請至 Google 帳戶的第三方權限中移除 PolyAsk 以確保撤銷生效。",
    syncPrivacy: "雲端記錄為純文字 JSON，不提供端對端加密；PolyAsk 僅要求 drive.appdata 權限。",
    syncActionFailed: "同步操作失敗",
    syncDiagnosticsTitle: "連線診斷",
    syncDiagnosticsDescription: "逐項檢查從應用程式設定到最近一次 Drive 同步的各個環節。",
    syncDiagnosticsShow: "展開連線診斷",
    syncDiagnosticsHide: "收合連線診斷",
    syncDiagnosticsCopy: "複製診斷報告",
    syncDiagnosticsCopied: "已複製診斷報告",
    syncDiagnosticsCopyFailed: "無法複製診斷報告",
    syncDiagnosticsRefreshFailed: "無法重新整理連線診斷",
    syncDiagnosticsPrivacy: "報告只包含應用程式與連線狀態，不包含權杖、帳戶資訊、提問內容、檔名或本機路徑。",
    syncStageOauthConfig: "OAuth 設定",
    syncStageBrowserAuth: "系統瀏覽器授權",
    syncStageTokenExchange: "授權碼交換",
    syncStageTokenStorage: "權杖儲存",
    syncStageDriveAccess: "Drive 存取權限",
    syncStageLastSync: "最近一次同步",
    syncDiagnosticOk: "通過",
    syncDiagnosticChecking: "正在檢查",
    syncDiagnosticWarning: "需要注意",
    syncDiagnosticFailed: "失敗",
    syncDiagnosticUnknown: "尚未檢查"
  }
} as const;
