export const WORKSPACE_COPY = {
  en: {
    retryCompact: "Retry",
    compareNeedsAnswers: "Wait for at least two selected sites to finish answering before comparing.",
    archiveBusy: "Wait for the current operation to finish before opening the result library. Saved question copies remain available in history.",
    compareBusy: "Comparison is unavailable while another operation is running.",
    selectedSummary: "{selected} / {total} selected",
    sendingSummary: "Sending to {count} sites",
    failedSummary: "{count} selected sites failed",
    cancelledSummary: "Sending was cancelled for {count} selected sites",
    mixedFailureSummary: "Selected sites: {failed} failed, {cancelled} cancelled",
    retryFailedSites: "Retry {count} failed sites",
    retryCancelledSites: "Retry {count} cancelled sites",
    retryFailedOrCancelledSites: "Retry {count} failed or cancelled sites",
    newSessionDone: "New sessions opened for {count} selected sites",
    newSessionPartial: "New sessions opened for {ok} sites; {failed} failed",
    scope: "Site scope",
    closeScope: "Close site scope",
    newSessionSelected: "New session for selected sites",
    allSites: "All",
    clearSites: "Clear",
    intlSites: "International",
    domesticSites: "Domestic",
    selectedSites: "Selected sites",
    savedGroups: "Saved groups",
    noSavedGroups: "No saved groups",
    groupNamePlaceholder: "Group name…",
    groupSelectionRequired: "Select at least 1 site to save a group",
    groupPresetReserved: "This scope is already available above",
    groupAlreadySaved: "This site combination is already saved",
    groupSaving: "Saving group…",
    saveGroup: "Save current selection",
    deleteGroup: "Delete {group}",
    confirmDeleteGroup: "Delete {group}?",
    confirmDelete: "Delete",
    cancelDelete: "Keep",
    workspaceActionFailed: "Workspace action failed",
    workbench: "Workbench",
    closeWorkbench: "Close workbench",
    selectSites: "Select sites",
    customScope: "Custom",
    sitesCompact: "Sites",
    chooseSavedGroup: "Choose a saved group",
    moreActions: "More actions",
    siteStatusSummary: "Page and adapter readiness",
    healthScopeSummary: "Current scope: {ready} ready · {signIn} sign-in · {error} issues · {unknown} unknown",
    healthReady: "Ready",
    healthSignIn: "Sign-in required",
    healthError: "Issue found",
    healthUnknown: "Status unknown",
    checkAgain: "Check again",
    checkingSiteHealth: "Checking…",
    healthLatestSend: "Latest send",
    healthNoRecentSend: "No send recorded",
    healthPageStatus: "Page status",
    healthAvailability: "Availability",
    healthAdapterChecks: "Adapter checks",
    healthCheckPassed: "Passed",
    healthCheckFailed: "Failed",
    healthCheckAdvisory: "Advisory",
    healthCheckedAt: "Last checked",
    healthNeverChecked: "Not checked yet",
    healthNoChecks: "No reliable adapter result yet",
    healthFocusSite: "Focus site",
    healthReloadBlocked: "Reload is unavailable while this site is working",
    healthEmptyScope: "Select at least one site to check its status",
    healthRequestFailed: "Could not check site status",
    healthReloaded: "Reloading {site}",
    healthReloadRejected: "{site} is working and cannot be reloaded right now",
    healthCopyReport: "Copy site diagnostic report",
    healthCopyReportCompact: "Copy report",
    healthReportCopied: "Site diagnostic report copied",
    healthReportCopyFailed: "Could not copy the site diagnostic report",
    hardReloadSite: "Force reload {site} (ignore cache)",
    clearSiteCache: "Clear cache & reload {site}",
    clearSiteCacheHint: "Clears this site's cache and service worker, then reloads. Sign-in is kept.",
    backToSiteStatus: "Back to site status",
    newSessionConfirmTitle: "Start new sessions?",
    newSessionConfirmMessage: "This will leave the current conversations on {count} selected sites and open a blank conversation on each.",
    newSessionConfirmAction: "Start new sessions",
    newSessionKeepCurrent: "Keep current conversations"
  },
  zhCN: {
    retryCompact: "重试",
    compareNeedsAnswers: "至少两个已选站点完成回答后，才能采集并比较。",
    compareBusy: "当前操作进行中，暂时无法采集并比较。",
    selectedSummary: "已选择 {selected} / {total}",
    sendingSummary: "正在向 {count} 个站点发送",
    failedSummary: "{count} 个已选站点失败",
    cancelledSummary: "{count} 个已选站点已取消发送",
    mixedFailureSummary: "已选站点：{failed} 个失败，{cancelled} 个已取消发送",
    retryFailedSites: "重试 {count} 个失败站点",
    retryCancelledSites: "重试 {count} 个已取消站点",
    retryFailedOrCancelledSites: "重试 {count} 个失败或已取消站点",
    newSessionDone: "已为 {count} 个已选站点新建会话",
    newSessionPartial: "已为 {ok} 个站点新建会话，{failed} 个失败",
    scope: "站点范围",
    closeScope: "关闭站点范围",
    newSessionSelected: "为已选站点新建会话",
    allSites: "全部",
    clearSites: "清空",
    intlSites: "国外",
    domesticSites: "国内",
    selectedSites: "已选站点",
    savedGroups: "已存分组",
    noSavedGroups: "暂无分组",
    groupNamePlaceholder: "分组名称…",
    groupSelectionRequired: "至少选择 1 个站点后才能保存分组",
    groupPresetReserved: "这一范围已在上方提供",
    groupAlreadySaved: "这一站点组合已经保存",
    groupSaving: "正在保存分组…",
    saveGroup: "保存当前选择",
    deleteGroup: "删除{group}",
    confirmDeleteGroup: "删除{group}？",
    confirmDelete: "删除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作区操作失败",
    workbench: "工作台",
    closeWorkbench: "关闭工作台",
    selectSites: "选择站点",
    customScope: "自定义",
    sitesCompact: "站点",
    chooseSavedGroup: "选择已存分组",
    moreActions: "更多操作",
    siteStatusSummary: "页面与适配器就绪情况",
    healthScopeSummary: "当前范围：{ready} 个可提问 · {signIn} 个需登录 · {error} 个异常 · {unknown} 个无法确认",
    healthReady: "可提问",
    healthSignIn: "需要登录",
    healthError: "发现异常",
    healthUnknown: "无法确认",
    checkAgain: "重新检查",
    checkingSiteHealth: "正在检查……",
    healthLatestSend: "最近一次发送",
    healthNoRecentSend: "暂无发送记录",
    healthPageStatus: "页面状态",
    healthAvailability: "可用性",
    healthAdapterChecks: "适配器检查",
    healthCheckPassed: "通过",
    healthCheckFailed: "未通过",
    healthCheckAdvisory: "提示",
    healthCheckedAt: "上次检查",
    healthNeverChecked: "尚未检查",
    healthNoChecks: "暂未取得可靠的适配器结果",
    healthFocusSite: "聚焦站点",
    healthReloadBlocked: "该站点正在工作，暂时不能重新加载",
    healthEmptyScope: "请先选择至少一个站点，再检查状态",
    healthRequestFailed: "无法检查站点状态",
    healthReloaded: "正在重新加载 {site}",
    healthReloadRejected: "{site} 正在工作，暂时不能重新加载",
    healthCopyReport: "复制站点诊断报告",
    healthCopyReportCompact: "复制报告",
    archiveBusy: "当前操作结束后可打开结果库；现在仍可在提问历史中查看已保存的副本。",
    healthReportCopied: "已复制站点诊断报告",
    healthReportCopyFailed: "无法复制站点诊断报告",
    hardReloadSite: "强制重新加载 {site}（忽略缓存）",
    clearSiteCache: "清除缓存并重新加载 {site}",
    clearSiteCacheHint: "清除该站点的缓存与 Service Worker 后重新加载，登录状态会保留",
    backToSiteStatus: "返回站点状态",
    newSessionConfirmTitle: "要新建会话吗？",
    newSessionConfirmMessage: "这会离开 {count} 个已选站点中的当前对话，并分别打开空白会话。",
    newSessionConfirmAction: "新建会话",
    newSessionKeepCurrent: "保留当前对话"
  },
  zhTW: {
    retryCompact: "重試",
    compareNeedsAnswers: "至少兩個已選網站完成回答後，才能擷取並比較。",
    compareBusy: "目前操作進行中，暫時無法擷取並比較。",
    selectedSummary: "已選取 {selected} / {total}",
    sendingSummary: "正在傳送到 {count} 個網站",
    failedSummary: "{count} 個已選網站失敗",
    cancelledSummary: "{count} 個已選網站已取消傳送",
    mixedFailureSummary: "已選網站：{failed} 個失敗，{cancelled} 個已取消傳送",
    retryFailedSites: "重試 {count} 個失敗網站",
    retryCancelledSites: "重試 {count} 個已取消網站",
    retryFailedOrCancelledSites: "重試 {count} 個失敗或已取消網站",
    newSessionDone: "已為 {count} 個已選網站新增對話",
    newSessionPartial: "已為 {ok} 個網站新增對話，{failed} 個失敗",
    scope: "網站範圍",
    closeScope: "關閉網站範圍",
    newSessionSelected: "為已選網站新增對話",
    allSites: "全部",
    clearSites: "清除",
    intlSites: "國外",
    domesticSites: "國內",
    selectedSites: "已選網站",
    savedGroups: "已儲存群組",
    noSavedGroups: "尚無群組",
    groupNamePlaceholder: "群組名稱…",
    groupSelectionRequired: "至少選取 1 個網站後才能儲存群組",
    groupPresetReserved: "此範圍已在上方提供",
    groupAlreadySaved: "此網站組合已儲存",
    groupSaving: "正在儲存群組…",
    saveGroup: "儲存目前選取",
    deleteGroup: "刪除{group}",
    confirmDeleteGroup: "刪除{group}？",
    confirmDelete: "刪除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作區操作失敗",
    workbench: "工作台",
    closeWorkbench: "關閉工作台",
    selectSites: "選擇網站",
    customScope: "自訂",
    sitesCompact: "網站",
    chooseSavedGroup: "選擇已儲存群組",
    moreActions: "更多操作",
    siteStatusSummary: "頁面與轉接器就緒狀況",
    healthScopeSummary: "目前範圍：{ready} 個可提問 · {signIn} 個需登入 · {error} 個異常 · {unknown} 個無法確認",
    healthReady: "可提問",
    healthSignIn: "需要登入",
    healthError: "發現異常",
    healthUnknown: "無法確認",
    checkAgain: "重新檢查",
    checkingSiteHealth: "正在檢查……",
    healthLatestSend: "最近一次傳送",
    healthNoRecentSend: "尚無傳送紀錄",
    healthPageStatus: "頁面狀態",
    healthAvailability: "可用性",
    healthAdapterChecks: "轉接器檢查",
    healthCheckPassed: "通過",
    healthCheckFailed: "未通過",
    healthCheckAdvisory: "提示",
    healthCheckedAt: "上次檢查",
    healthNeverChecked: "尚未檢查",
    healthNoChecks: "尚未取得可靠的轉接器結果",
    healthFocusSite: "聚焦網站",
    healthReloadBlocked: "此網站正在工作，暫時無法重新載入",
    healthEmptyScope: "請先選取至少一個網站，再檢查狀態",
    healthRequestFailed: "無法檢查網站狀態",
    healthReloaded: "正在重新載入 {site}",
    healthReloadRejected: "{site} 正在工作，暫時無法重新載入",
    healthCopyReport: "複製網站診斷報告",
    healthCopyReportCompact: "複製報告",
    archiveBusy: "目前操作結束後可開啟結果庫；目前仍可在提問歷史中查看已儲存的副本。",
    healthReportCopied: "已複製網站診斷報告",
    healthReportCopyFailed: "無法複製網站診斷報告",
    hardReloadSite: "強制重新載入 {site}（忽略快取）",
    clearSiteCache: "清除快取並重新載入 {site}",
    clearSiteCacheHint: "清除此網站的快取與 Service Worker 後重新載入，登入狀態會保留",
    backToSiteStatus: "返回網站狀態",
    newSessionConfirmTitle: "要新增對話嗎？",
    newSessionConfirmMessage: "這會離開 {count} 個已選網站中的目前對話，並分別開啟空白對話。",
    newSessionConfirmAction: "新增對話",
    newSessionKeepCurrent: "保留目前對話"
  }
} as const;
